namespace Fenrir.Contracts.Packets.Shared;

/// <summary>
///     Shared wire-zero <see cref="AvatarInfo" /> template, used by both LoginServer (LC_CREATE_AVATAR_RECV)
///     and GameServer (ZC_REGISTER_AVATAR_RECV) — the two servers each project a persisted character onto this
///     same struct, but neither Application project references the other (architecture reference §3.3: each
///     executable's application layer is independent), so the ~190-field zero template lives here in Contracts,
///     the one layer both already depend on. Progression/inventory/quest state is entirely M1-out-of-scope, so
///     every field starts at its wire-zero value; callers only ever override the handful of fields the DB
///     actually tracks, via a `with` expression.
/// </summary>
public static class AvatarInfoTemplates
{
    /// <summary>
    ///     Every <see cref="AvatarInfo" /> field at its wire-zero value: 0 for scalars, "" for
    ///     <c>[FixedString]</c> (the codec zero-fills up to the declared length itself — never hand-pad), a
    ///     same-length-N array of zeros for <c>[FixedArray]</c> int arrays (N must match this exact property's
    ///     attribute, not a neighbor's), and a same-length-N array of "" for <c>[FixedArray] [FixedString]</c> string
    ///     rows (never a bare <c>new string[N]</c>, which would leave <see langword="null" /> entries the codec
    ///     cannot write).
    /// </summary>
    public static readonly AvatarInfo Zeroed = new()
    {
        VisibleState = 0,
        SpecialState = 0,
        PlayTime1 = 0,
        PlayTime2 = 0,
        KillOtherTribe = 0,
        Name = "",
        Tribe = 0,
        PreviousTribe = 0,
        Gender = 0,
        HeadType = 0,
        FaceType = 0,
        Level1 = 0,
        Level2 = 0,
        Exp1 = 0,
        Exp2 = 0,
        Vit = 0,
        Str = 0,
        Int = 0,
        Dex = 0,
        EatLifePotion = 0,
        EatManaPotion = 0,
        StatPoint = 0,
        SkillPoint = 0,
        Equip = new int[52],
        InventoryDate = 0,
        Money = 0,
        Inventory = new int[768],
        TradeMoney = 0,
        Trade = new int[32],
        StoreDate = 0,
        StoreMoney = 0,
        StoreItem = new int[224],
        Skill = new int[80],
        HotKey = new int[126],
        QuestInfo = new int[5],
        Friend = ZeroStrings(10),
        Teacher = "",
        Student = "",
        TeacherPoint = 0,
        GuildName = "",
        GuildRole = 0,
        CallName = "",
        GuildMarkNum = 0,
        GuildMarkEffect = 0,
        LogoutInfo = new int[6],
        ProtectForDeath = 0,
        ProtectForDestroy = 0,
        FightingGodForDestroy = 0,
        DoubleExpTime1 = 0,
        DoubleKillNumTime = 0,
        DoubleKillExpTime = 0,
        Zone175Time = 0,
        Zone101Time = 0,
        Zone125Time = 0,
        Zone126Time = 0,
        KillMonsterNum = 0,
        KillMonsterNum2 = 0,
        KillMonsterNum3 = 0,
        LevelZoneKeyNum = 0,
        SearchAndBuyDate = 0,
        LifePotionConvertNum = 0,
        ManaPotionConvertNum = 0,
        TribeVoteDate = 0,
        AutoLifeRatio = 0,
        AutoManaRatio = 0,
        EatStrPotion = 0,
        EatDexPotion = 0,
        Animal = new int[10],
        AnimalIndex = 0,
        AnimalTime = 0,
        AddItemValue = 0,
        HighItemValue = 0,
        DropItemTime = 0,
        Title = 0,
        DoubleKillNumTime2 = 0,
        Halo = 0,
        BonusItemValue = 0,
        BonusItemLevel = 0,
        KillOtherTribeEvent = 0,
        TeacherPointEvent = 0,
        PlayTimeEvent = 0,
        ProtectForHalo = 0,
        UseOrnament = 0,
        SilverTime = 0,
        Zone234Time = 0,
        Zone235Time = 0,
        Zone236Time = 0,
        Zone237Time = 0,
        Zone238Time = 0,
        Zone239Time = 0,
        Zone240Time = 0,
        RebirthNum = 0,
        Zone241Time = 0,
        ChallengeNum = 0,
        GoldTime = 0,
        Zone234X2Time = 0,
        Zone235X2Time = 0,
        BattleEnterNum = 0,
        BattleEnterDate = 0,
        PlayTime3 = 0,
        BuffX2Time = 0,
        DoubleExpTime2 = 0,
        ReturnTribeNum = 0,
        PetExpX2Time = 0,
        GuildMoneyTime = 0,
        SaveMoney = 0,
        SaveItem = new int[112],
        PartyName = ZeroStrings(5),
        Costume = new int[10],
        CostumeDate = new int[10],
        CostumeExpireDate = new int[10],
        CostumeIndex = 0,
        DmgBoost = 0,
        HPBoost = 0,
        CriBoost = 0,
        AutoBuffTime = 0,
        AutoBuffSkill = new int[16],
        DungeonEvent = 0,
        ImproveItemValue = 0,
        Zone270Score = 0,
        TimeEffectTime = 0,
        StateTimeEffect = 0,
        SelectTimeEffectType = 0,
        InvenSocket = new int[384],
        EquipSocket = new int[39],
        TradeSocket = new int[24],
        StoreSocket = new int[168],
        SaveSocket = new int[84],
        AutoTime = 0,
        AutoTime2 = 0,
        AutoState = 0,
        AutoHunt = new AutoHunt
        {
            BuffType = 0,
            BuffStore = new int[16],
            HuntType = 0,
            AttackType = new int[4],
            MonNum = 0,
            ItemType = 0,
            InvenCmd = 0,
            DeathCmd = 0,
            AnimalPreyCmd = 0,
            AnimalFoodCmd = 0
        },
        BigMoney = 0,
        BigTradeMoney = 0,
        BigStoreMoney = 0,
        BigSaveMoney = 0,
        EatElePotion = 0,
        Zone050Time = 0,
        ProtectForRefine = 0,
        GoldenLakeTime = 0,
        PreventForSmelt = 0,
        BloodCoin = 0,
        HeavenlyTicket = 0,
        Tevushi = 0,
        MammothRoad = 0,
        Zone050Time2 = 0,
        FishingZoneDate = 0,
        ProxyShopDate = 0,
        B4GHPElixir = 0,
        B4GMPElixir = 0,
        B4GStrElixir = 0,
        B4GDexElixir = 0,
        KillCount = 0,
        KillCountTime = 0,
        RankPoint = 0,
        RankPointDate = 0,
        RankBuffType = 0,
        TribeNotifyNum = 0,
        SpeakerCount = 0,
        AnimalExpActivity = new int[10],
        AnimalPower = new int[10],
        AnimalDoubleExp = 0,
        EventValue1 = 0,
        EventValue2 = 0,
        EventValue3 = 0,
        EventValue4 = 0,
        AnimalAbsorbTime = 0,
        AnimalAbsorbState = 0,
        CapsuleCashPoint = 0,
        RageGauge = 0,
        RageBuffTime = 0,
        RageBuffState = 0,
        RageBuffPotion = 0,
        RageDoubleEffect = 0,
        WarriorScroll = 0,
        UseItemMonth = 0,
        UseItemOnce = 0,
        HeroPoint = 0,
        HeroPointDate = 0,
        KillMonsterNumForHeroPoint = 0,
        WarriorPill = 0,
        OllehEventPoint = 0,
        ProtectForWing = 0,
        TeacherPointDate = 0,
        ProtectForDestroy2 = 0,
        PetBagDate = 0,
        PetBag = new int[20],
        MissionDate = new MissionDate
        {
            JoinWar = 0,
            KillOtherTribe = 0,
            KillMonster = 0,
            PlayTime = 0
        },
        CriticalSpeedTime = 0,
        DefenceUpNum = 0,
        Zone038Ticket = 0,
        HyunKyungMonster = 0,
        Bottle = new int[10],
        BottleCount = new int[10],
        BottleIndex = 0,
        BottleTime = 0,
        MixSkill = new int[28],
        MixSkillBuffTime = 0,
        BywonjiTime = 0,
        UniqueSkill = 0,
        UniqueSkillBuffTime = 0,
        BackSoul = 0,
        Premium = 0L,
        ProtectForCombine = 0,
        PlayOnlineTime = 0,
        PlayOnlineTime2 = 0,
        ProtectForCostume = 0,
        WarPoint = 0,
        PopUpKillAvt = 0,
        PopUpKillMonster = 0,
        PopUpKillAvtWar = 0,
        StellarCore = new int[10],
        StellarCoreExpireDate = new int[10],
        StellarCoreIndex = 0,
        InvenExpireDate = new int[128],
        EquipExpireDate = new int[13],
        TradeExpireDate = new int[8],
        StoreExpireDate = new int[56],
        SaveExpireDate = new int[28],
        WarKillCount = 0,
        HSBStoneRewardCheck = 0,
        GBox2249 = 0,
        GBox8114 = 0,
        GBox8115 = 0,
        GBox8111 = 0,
        RuneSystem = new int[4],
        RuneSystemStat = new int[4]
    };

    // Enumerable.Repeat(...).ToArray() would also work but allocates a LINQ iterator per call for what is really
    // just a fixed-size fill; a plain loop keeps this on the same footing as the int[] literals above.
    private static string[] ZeroStrings(int count)
    {
        var result = new string[count];
        for (var i = 0; i < count; i++)
            result[i] = "";

        return result;
    }
}
