<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c71f23c2-ba7d-4978-bdb5-b3607f8eb507</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Servers\Fenrir.LoginServer\Fenrir.LoginServer.csproj"/>
    <ProjectReference Include="..\..\Servers\Fenrir.GameServer\Fenrir.GameServer.csproj"/>
    <ProjectReference Include="..\..\Tools\Fenrir.Tools.DbMigrator\Fenrir.Tools.DbMigrator.csproj"/>
  </ItemGroup>

</Project>
