using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

internal static class OpcodeRegistryEmitter
{
    public const string HintName = "OpcodeRegistry.g.cs";

    public static string Emit(ImmutableArray<TypeModel> packets)
    {
        var ordered = packets
            .OrderBy(p => p.Server)
            .ThenBy(p => p.Direction)
            .ThenBy(p => p.Opcode)
            .ToImmutableArray();

        var (className, namespaceName) = ordered[0].Server switch
        {
            FenrirServer.Login => ("LoginOpcodeRegistry", "Fenrir.Application.Login"),
            FenrirServer.Zone => ("ZoneOpcodeRegistry", "Fenrir.Application.Game"),
            _ => ("CenterOpcodeRegistry", "Fenrir.Cluster")
        };

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {namespaceName};");
        writer.Line();
        writer.Line(
            "/// <summary>(Server, Direction, Opcode) → (frame size, type name) table generated from discovered [FenrirPacket].</summary>");
        writer.Line($"public static class {className}");
        writer.OpenBrace();

        writer.Line(
            "public static int FrameSizeOf(global::Fenrir.Core.Wire.FenrirServer server, global::Fenrir.Core.Wire.FenrirDirection direction, byte opcode) => (server, direction, opcode) switch");
        writer.OpenBrace();
        foreach (var packet in ordered)
        {
            var incomingHeaderSize = packet.Server == FenrirServer.Center
                ? WireHeaderSizes.DefaultPacketSize
                : WireHeaderSizes.ClientPacketSize;
            var headerSize = packet.Direction == FenrirDirection.Incoming
                ? incomingHeaderSize
                : WireHeaderSizes.DefaultPacketSize;
            var frameSize = packet.FieldsSize + headerSize;
            writer.Line(
                $"({ServerLiteral(packet.Server)}, {DirectionLiteral(packet.Direction)}, {packet.Opcode}) => {frameSize},");
        }

        writer.Line(
            "_ => throw new global::System.ArgumentOutOfRangeException(nameof(opcode), opcode, $\"Unknown legacy opcode for ({server}, {direction}).\"),");
        writer.CloseBraceSemicolon();

        writer.Line();
        writer.Line(
            "public static string NameOf(global::Fenrir.Core.Wire.FenrirServer server, global::Fenrir.Core.Wire.FenrirDirection direction, byte opcode) => (server, direction, opcode) switch");
        writer.OpenBrace();
        foreach (var packet in ordered)
            writer.Line(
                $"({ServerLiteral(packet.Server)}, {DirectionLiteral(packet.Direction)}, {packet.Opcode}) => \"{packet.FullTypeName}\",");
        writer.Line(
            "_ => throw new global::System.ArgumentOutOfRangeException(nameof(opcode), opcode, $\"Unknown legacy opcode for ({server}, {direction}).\"),");
        writer.CloseBraceSemicolon();

        writer.Line();
        EmitProvider(writer, ordered);

        writer.CloseBrace();
        return writer.ToString();
    }

    private static void EmitProvider(IndentedWriter writer, ImmutableArray<TypeModel> ordered)
    {
        var entries = ordered
            .Where(p => p.Direction == FenrirDirection.Incoming)
            .ToImmutableArray();

        writer.Line(
            "public static readonly global::Fenrir.Network.Abstractions.IOpcodeFrameSizeProvider Provider = new ProviderImpl();");
        writer.Line();
        writer.Line("private sealed class ProviderImpl : global::Fenrir.Network.Abstractions.IOpcodeFrameSizeProvider");
        writer.OpenBrace();
        writer.Line("public bool TryGetFrameSize(byte opcode, out int frameSize)");
        writer.OpenBrace();
        writer.Line("frameSize = opcode switch");
        writer.OpenBrace();
        foreach (var packet in entries)
        {
            var headerSize = packet.Server == FenrirServer.Center
                ? WireHeaderSizes.DefaultPacketSize
                : WireHeaderSizes.ClientPacketSize;
            writer.Line($"{packet.Opcode} => {packet.FieldsSize + headerSize},");
        }
        writer.Line("_ => -1,");
        writer.CloseBraceSemicolon();
        writer.Line("return frameSize >= 0;");
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static string ServerLiteral(FenrirServer server)
    {
        return server switch
        {
            FenrirServer.Login => "global::Fenrir.Core.Wire.FenrirServer.Login",
            FenrirServer.Zone => "global::Fenrir.Core.Wire.FenrirServer.Zone",
            _ => "global::Fenrir.Core.Wire.FenrirServer.Center"
        };
    }

    private static string DirectionLiteral(FenrirDirection direction)
    {
        return direction == FenrirDirection.Incoming
            ? "global::Fenrir.Core.Wire.FenrirDirection.Incoming"
            : "global::Fenrir.Core.Wire.FenrirDirection.Outgoing";
    }
}
