using System;
using System.Globalization;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

internal static class PacketEmitter
{
    public static string Emit(TypeModel model)
    {
        var writer = new IndentedWriter();
        var sizeMember = model.IsPacket ? "PayloadSize" : "WireSize";

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {model.Namespace};");
        writer.Line();
        writer.Line($"partial record struct {model.TypeName}");
        writer.OpenBrace();

        if (model.IsPacket)
        {
            writer.Line($"public static byte Opcode => {FormatByteLiteral(model.Opcode)};");
            writer.Line();
        }

        writer.Line($"public static int {sizeMember} => {model.FieldsSize};");

        var emitTryRead = !model.IsPacket || model.ImplementsIncoming;
        var emitWrite = !model.IsPacket || model.ImplementsOutgoing;

        if (model.IsPacket && model.ImplementsOutgoing)
        {
            writer.Line();
            writer.Line(
                $"public static global::Fenrir.Core.Wire.WireObfuscationMode Obfuscation => global::Fenrir.Core.Wire.WireObfuscationMode.{model.Obfuscation};");
            writer.Line();
            writer.Line($"public static bool Compressed => {(model.Compressed ? "true" : "false")};");
        }

        if (emitTryRead)
        {
            writer.Line();
            EmitTryRead(writer, model, sizeMember);
        }

        if (emitWrite)
        {
            writer.Line();
            EmitWrite(writer, model, sizeMember);
        }

        writer.CloseBrace();

        return writer.ToString();
    }

    private static void EmitTryRead(IndentedWriter writer, TypeModel model, string sizeMember)
    {
        writer.Line(
            $"public static bool TryRead(global::System.ReadOnlySpan<byte> source, out {model.TypeName} packet)");
        writer.OpenBrace();
        writer.Line($"if (source.Length < {sizeMember})");
        writer.OpenBrace();
        writer.Line("packet = default;");
        writer.Line("return false;");
        writer.CloseBrace();

        if (model.Fields.Length > 0)
        {
            writer.Line();
            writer.Line("var reader = new global::Fenrir.Core.Wire.MessageReader(source);");
        }

        foreach (var field in model.Fields)
        {
            if (field.ReservedBefore > 0)
                writer.Line($"reader.Skip({field.ReservedBefore});");

            var localName = "v_" + field.PropertyName;

            Action emitField = field.Shape switch
            {
                FieldShape.Int32 => () => writer.Line($"var {localName} = reader.ReadInt32();"),
                FieldShape.UInt32 => () => writer.Line($"var {localName} = reader.ReadUInt32();"),
                FieldShape.Byte => () => writer.Line($"var {localName} = reader.ReadByte();"),
                FieldShape.Single => () => writer.Line($"var {localName} = reader.ReadSingle();"),
                FieldShape.Int64 => () => writer.Line($"var {localName} = reader.ReadInt64();"),
                FieldShape.FixedString => () => writer.Line(
                    $"var {localName} = reader.ReadFixedString({field.StringLength});"),
                FieldShape.Int32Array => () => writer.Line(
                    $"var {localName} = reader.ReadInt32Array({field.OwnSize});"),
                FieldShape.SingleArray => () => writer.Line(
                    $"var {localName} = reader.ReadSingleArray({field.OwnSize});"),
                FieldShape.ByteArray => () => writer.Line(
                    $"var {localName} = reader.ReadByteArray({field.OwnSize});"),
                FieldShape.FixedStringArray => () => writer.Line(
                    $"var {localName} = reader.ReadFixedStringRows({field.OwnSize}, {field.StringLength});"),
                FieldShape.Nested => () =>
                {
                    writer.Line(
                        $"if (!{field.NestedTypeFullName}.TryRead(reader.ReadSlice({field.OwnSize}), out var {localName}))");
                    writer.OpenBrace();
                    writer.Line("packet = default;");
                    writer.Line("return false;");
                    writer.CloseBrace();
                },
                FieldShape.NestedArray => () =>
                {
                    writer.Line($"var {localName}_slice = reader.ReadSlice({field.OwnSize});");
                    writer.Line($"var {localName} = new {field.NestedTypeFullName}[{field.ElementCount}];");
                    writer.Line($"for (var i = 0; i < {field.ElementCount}; i++)");
                    writer.OpenBrace();
                    writer.Line(
                        $"if (!{field.NestedTypeFullName}.TryRead({localName}_slice.Slice(i * {field.NestedSize}, {field.NestedSize}), out {localName}[i]))");
                    writer.OpenBrace();
                    writer.Line("packet = default;");
                    writer.Line("return false;");
                    writer.CloseBrace();
                    writer.CloseBrace();
                },
                _ => () => throw new NotSupportedException(
                    $"PacketEmitter.EmitTryRead has no case for FieldShape.{field.Shape} (field '{field.PropertyName}').")
            };

            emitField();
        }

        writer.Line();

        if (model.Fields.Length == 0)
        {
            writer.Line($"packet = new {model.TypeName}();");
        }
        else
        {
            writer.Line($"packet = new {model.TypeName}");
            writer.OpenBrace();
            foreach (var field in model.Fields)
                writer.Line($"{field.PropertyName} = v_{field.PropertyName},");
            writer.CloseBraceSemicolon();
        }

        writer.Line("return true;");
        writer.CloseBrace();
    }

    private static void EmitWrite(IndentedWriter writer, TypeModel model, string sizeMember)
    {
        writer.Line("public int Write(global::System.Span<byte> destination)");
        writer.OpenBrace();

        if (model.Fields.Length > 0)
            writer.Line("var writer = new global::Fenrir.Core.Wire.MessageWriter(destination);");

        FieldModel? legacyUidField = null;

        foreach (var field in model.Fields)
        {
            if (field.ReservedBefore > 0)
                writer.Line($"writer.Skip({field.ReservedBefore});");

            var access = field.PropertyName;

            var needsSliceLocal = field.AvatarXor != AvatarXorKind.None || field.IsLegacyUidField;
            var localName = "v_" + field.PropertyName + "_slice";
            var assignPrefix = needsSliceLocal ? $"var {localName} = " : "";

            Action emitField = field.Shape switch
            {
                FieldShape.Int32 => () => writer.Line($"{assignPrefix}writer.WriteInt32({access});"),
                FieldShape.UInt32 => () => writer.Line($"{assignPrefix}writer.WriteUInt32({access});"),
                FieldShape.Byte => () => writer.Line($"{assignPrefix}writer.WriteByte({access});"),
                FieldShape.Single => () => writer.Line($"{assignPrefix}writer.WriteSingle({access});"),
                FieldShape.Int64 => () => writer.Line($"{assignPrefix}writer.WriteInt64({access});"),
                FieldShape.FixedString => () => writer.Line(
                    $"{assignPrefix}writer.WriteFixedString({access}, {field.StringLength});"),
                FieldShape.Int32Array => () => writer.Line(
                    $"{assignPrefix}writer.WriteInt32Array({access}, {field.OwnSize});"),
                FieldShape.SingleArray => () => writer.Line(
                    $"{assignPrefix}writer.WriteSingleArray({access}, {field.OwnSize});"),
                FieldShape.ByteArray => () => writer.Line(
                    $"{assignPrefix}writer.WriteByteArray({access}, {field.OwnSize});"),
                FieldShape.FixedStringArray => () => writer.Line(
                    $"{assignPrefix}writer.WriteFixedStringRows({access}, {field.OwnSize}, {field.StringLength});"),
                FieldShape.Nested => () =>
                {
                    writer.Line($"var {localName} = writer.Reserve({field.OwnSize});");
                    writer.Line($"{access}.Write({localName});");
                },
                FieldShape.NestedArray => () =>
                {
                    writer.Line($"var {localName} = writer.Reserve({field.OwnSize});");
                    writer.Line($"for (var i = 0; i < {field.ElementCount}; i++)");
                    writer.OpenBrace();
                    writer.Line($"{access}[i].Write({localName}.Slice(i * {field.NestedSize}, {field.NestedSize}));");
                    writer.CloseBrace();
                },
                _ => () => throw new NotSupportedException(
                    $"PacketEmitter.EmitWrite has no case for FieldShape.{field.Shape} (field '{field.PropertyName}').")
            };

            emitField();

            if (field.AvatarXor != AvatarXorKind.None)
                switch (field.AvatarXor)
                {
                    case AvatarXorKind.Int:
                        writer.Line($"global::Fenrir.Core.Wire.WireXor.XorInt({localName});");
                        break;
                    case AvatarXorKind.IntArray:
                        writer.Line($"global::Fenrir.Core.Wire.WireXor.XorIntArray({localName});");
                        break;
                    case AvatarXorKind.Char:
                        writer.Line($"global::Fenrir.Core.Wire.WireXor.XorChar({localName});");
                        break;
                    case AvatarXorKind.Char2:
                        writer.Line(
                            $"global::Fenrir.Core.Wire.WireXor.XorChar2Rows({localName}, {field.AvatarXorRowLength});");
                        break;
                }

            if (field.IsLegacyUidField)
                legacyUidField = field;
        }

        if (legacyUidField is not null)
        {
            writer.Line();
            writer.Line(
                "// [ObfuscatedUidField] (§3.3): double-XOR of tID, independent of the global XOR_PACKET applied later by the send layer.");
            writer.Line(
                $"global::Fenrir.Core.Wire.WireXor.ApplyUidXor(v_{legacyUidField.PropertyName}_slice);");
        }

        writer.Line();
        writer.Line($"return {sizeMember};");
        writer.CloseBrace();
    }

    private static string FormatByteLiteral(byte value)
    {
        return value.ToString(CultureInfo.InvariantCulture);
    }
}
