<Project>
  <PropertyGroup Condition="'$(FenrirExecutable)' == 'true'">
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StackTraceSupport>true</StackTraceSupport>
    <EventSourceSupport>true</EventSourceSupport>

    <NoWarn>$(NoWarn);IL2104;IL3053</NoWarn>

    <InvariantGlobalization>false</InvariantGlobalization>

    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>
</Project>
