<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fenrir.Network.Dispatch\Fenrir.Network.Dispatch.csproj"/>
    <ProjectReference Include="..\Fenrir.Network.Serialization.Zone\Fenrir.Network.Serialization.Zone.csproj"/>
  </ItemGroup>

</Project>
