using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

internal static class OpcodeRegistryEmitter
{
    public const string HintName = "OpcodeRegistry.g.cs";

    public static string Emit(ImmutableArray<TypeModel> packets, string namespaceName)
    {
        var ordered = packets
            .OrderBy(p => p.Server)
            .ThenBy(p => p.Direction)
            .ThenBy(p => p.Opcode)
            .ToImmutableArray();

        var className = EmittedNames.OpcodeRegistry(ordered[0].Server);

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {namespaceName};");
        writer.Line();
        writer.Line(
            "/// <summary>(Server, Direction, Opcode) → (frame size, type name) table generated from discovered [FenrirPacket].</summary>");
        writer.Line($"public static class {className}");
        writer.OpenBrace();

        writer.Line(
            $"public static int FrameSizeOf({WellKnownNames.FenrirServerEnum} server, {WellKnownNames.FenrirDirectionEnum} direction, byte opcode) => (server, direction, opcode) switch");
        writer.OpenBrace();
        foreach (var packet in ordered)
        {
            var headerSize = packet.Direction == FenrirDirection.Incoming
                ? WireHeaderSizes.ClientPacketSize
                : WireHeaderSizes.DefaultPacketSize;
            var frameSize = packet.FieldsSize + headerSize;
            writer.Line(
                $"({ServerLiteral(packet.Server)}, {DirectionLiteral(packet.Direction)}, {packet.Opcode}) => {frameSize},");
        }

        writer.Line(
            "_ => throw new global::System.ArgumentOutOfRangeException(nameof(opcode), opcode, $\"Unknown legacy opcode for ({server}, {direction}).\"),");
        writer.CloseBraceSemicolon();

        writer.Line();
        writer.Line(
            $"public static string NameOf({WellKnownNames.FenrirServerEnum} server, {WellKnownNames.FenrirDirectionEnum} direction, byte opcode) => (server, direction, opcode) switch");
        writer.OpenBrace();
        foreach (var packet in ordered)
            writer.Line(
                $"({ServerLiteral(packet.Server)}, {DirectionLiteral(packet.Direction)}, {packet.Opcode}) => \"{packet.FullTypeName}\",");
        writer.Line(
            "_ => throw new global::System.ArgumentOutOfRangeException(nameof(opcode), opcode, $\"Unknown legacy opcode for ({server}, {direction}).\"),");
        writer.CloseBraceSemicolon();

        writer.Line();
        EmitProvider(writer, ordered);

        writer.CloseBrace();
        return writer.ToString();
    }

    private static void EmitProvider(IndentedWriter writer, ImmutableArray<TypeModel> ordered)
    {
        var entries = ordered
            .Where(p => p.Direction == FenrirDirection.Incoming)
            .ToImmutableArray();

        writer.Line(
            $"public static readonly {WellKnownNames.IOpcodeFrameSizeProvider} Provider = new ProviderImpl();");
        writer.Line();
        writer.Line($"private sealed class ProviderImpl : {WellKnownNames.IOpcodeFrameSizeProvider}");
        writer.OpenBrace();
        writer.Line("public bool TryGetFrameSize(byte opcode, out int frameSize)");
        writer.OpenBrace();
        writer.Line("frameSize = opcode switch");
        writer.OpenBrace();
        foreach (var packet in entries)
        {
            var headerSize = WireHeaderSizes.ClientPacketSize;
            writer.Line($"{packet.Opcode} => {packet.FieldsSize + headerSize},");
        }

        writer.Line("_ => -1,");
        writer.CloseBraceSemicolon();
        writer.Line("return frameSize >= 0;");
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static string ServerLiteral(FenrirServer server)
    {
        return server switch
        {
            FenrirServer.Login => $"{WellKnownNames.FenrirServerEnum}.Login",
            FenrirServer.Zone => $"{WellKnownNames.FenrirServerEnum}.Zone",
            _ => throw new System.ArgumentOutOfRangeException(nameof(server), server, null)
        };
    }

    private static string DirectionLiteral(FenrirDirection direction)
    {
        return direction == FenrirDirection.Incoming
            ? $"{WellKnownNames.FenrirDirectionEnum}.Incoming"
            : $"{WellKnownNames.FenrirDirectionEnum}.Outgoing";
    }
}
