using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

internal static class SessionStateGateEmitter
{
    public const string HintName = "SessionStateGate.g.cs";
    private const byte ZoneInWorldState = 3;

    public static string Emit(ImmutableArray<TypeModel> packets, string namespaceName)
    {
        var server = packets[0].Server;
        var className = EmittedNames.SessionStateGate(server);
        var stateEnum = server switch
        {
            FenrirServer.Login => WellKnownNames.LoginSessionStateEnum,
            FenrirServer.Zone => WellKnownNames.ZoneSessionStateEnum,
            _ => throw new ArgumentOutOfRangeException(nameof(server), server, null)
        };

        var entries = packets
            .Where(p => p.Direction == FenrirDirection.Incoming &&
                        (server == FenrirServer.Zone || p.AllowedStates.Length > 0))
            .OrderBy(p => p.Opcode)
            .ToImmutableArray();

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {namespaceName};");
        writer.Line();
        writer.Line($"public static class {className}");
        writer.OpenBrace();

        EmitAllows(writer, server, stateEnum, entries);

        writer.CloseBrace();
        return writer.ToString();
    }

    private static void EmitAllows(IndentedWriter writer, FenrirServer server, string stateEnum,
        ImmutableArray<TypeModel> entries)
    {
        writer.Line($"public static bool Allows({stateEnum} state, byte opcode)");
        writer.OpenBrace();
        writer.Line("return opcode switch");
        writer.OpenBrace();

        foreach (var packet in entries)
        {
            IEnumerable<byte> allowedStates = server == FenrirServer.Zone &&
                                              packet.AllowedStates.Contains(ZoneInWorldState)
                ? [ZoneInWorldState]
                : packet.AllowedStates;
            var condition = string.Join(" || ", allowedStates.Select(s => $"state == ({stateEnum}){s}"));
            writer.Line($"{packet.Opcode} => {condition},");
        }

        writer.Line(server == FenrirServer.Zone ? "_ => false," : "_ => true,");
        writer.CloseBraceSemicolon();
        writer.CloseBrace();
    }
}
