<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Using Include="Fenrir.Core.Abstractions"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fenrir.Generators\Fenrir.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>
</Project>
