-- Legacy ITEM_INFO (post-runtime-patch data, i.e. what the live legacy server actually serves); one row per record where Index != 0.
-- GainSkillNumber is a nullable FK to world.Skills despite the "Number" name -- it's a skill reference, not a quantity (0 -> NULL). BonusSkillInfo[8][2] normalizes into world.ItemBonusSkills.
CREATE TABLE world.Items
(
    ItemId               INT      NOT NULL,
    Name                 NVARCHAR(25) NOT NULL,
    Description1         NVARCHAR(51) NULL,
    Description2         NVARCHAR(51) NULL,
    Description3         NVARCHAR(51) NULL,
    Type                 TINYINT  NOT NULL,
    Sort                 TINYINT  NOT NULL,
    DataNumber2D         SMALLINT NOT NULL,
    DataNumber3D         TINYINT  NOT NULL,
    AddDataNumber3D      TINYINT  NOT NULL, -- always 0 in current data; reserved slot in ITEM_INFO, kept for fidelity
    Level                SMALLINT NOT NULL,
    MartialLevel         TINYINT  NOT NULL,
    EquipInfo1           TINYINT  NOT NULL,
    EquipInfo2           TINYINT  NOT NULL,
    BuyCost              INT      NOT NULL,
    SellCost             INT      NOT NULL,
    BuyCost2             INT      NOT NULL,
    LevelLimit           SMALLINT NOT NULL,
    MartialLevelLimit    TINYINT  NOT NULL,
    CheckMonsterDrop     TINYINT  NOT NULL,
    CheckNpcSell         TINYINT  NOT NULL,
    CheckNpcShop         TINYINT  NOT NULL,
    CheckAvatarDrop      TINYINT  NOT NULL,
    CheckAvatarTrade     TINYINT  NOT NULL,
    CheckAvatarShop      TINYINT  NOT NULL,
    CheckImprove         TINYINT  NOT NULL,
    CheckHighImprove     TINYINT  NOT NULL,
    CheckHighItem        TINYINT  NOT NULL,
    CheckLowItem         TINYINT  NOT NULL,
    CheckExchange        TINYINT  NOT NULL,
    CheckSetItem         TINYINT  NOT NULL,
    CheckDateItem        TINYINT  NOT NULL, -- despite the "Check" prefix this ranges 0-30, not boolean (likely a day count)
    Strength             SMALLINT NOT NULL,
    Dexterity            SMALLINT NOT NULL,
    Vitality             SMALLINT NOT NULL,
    Intelligent          SMALLINT NOT NULL,
    Luck                 SMALLINT NOT NULL,
    AttackPower          SMALLINT NOT NULL,
    DefensePower         SMALLINT NOT NULL,
    AttackSuccess        SMALLINT NOT NULL,
    AttackBlock          SMALLINT NOT NULL,
    ElementAttackPower   SMALLINT NOT NULL,
    ElementDefensePower  SMALLINT NOT NULL,
    Critical             TINYINT  NOT NULL,
    PotionType1          SMALLINT NOT NULL,
    PotionType2          SMALLINT NOT NULL,
    GainSkillNumber      INT NULL,
    LastAttackBonusInfo1 SMALLINT NOT NULL,
    LastAttackBonusInfo2 SMALLINT NOT NULL,
    CapeInfo1            TINYINT  NOT NULL,
    CapeInfo2            TINYINT  NOT NULL,
    CapeInfo3            TINYINT  NOT NULL,
    CONSTRAINT PK_Items PRIMARY KEY CLUSTERED (ItemId),
    CONSTRAINT FK_Items_Levels_Level FOREIGN KEY (Level) REFERENCES world.Levels (Level),
    CONSTRAINT FK_Items_Levels_LevelLimit FOREIGN KEY (LevelLimit) REFERENCES world.Levels (Level),
    CONSTRAINT FK_Items_Skills_GainSkillNumber FOREIGN KEY (GainSkillNumber) REFERENCES world.Skills (SkillId)
);
