CREATE TABLE world.Quests
(
    QuestId          INT          NOT NULL,
    Subject          NVARCHAR(51) NOT NULL,
    Category         TINYINT      NOT NULL,
    Step             SMALLINT     NOT NULL,
    Level            SMALLINT     NOT NULL,
    Type             TINYINT      NOT NULL,
    Sort             TINYINT      NOT NULL,
    SummonZoneNumber SMALLINT     NULL,
    SummonPosX       INT          NULL,
    SummonPosY       INT          NULL,
    SummonPosZ       INT          NULL,
    StartNPCNumber   INT          NOT NULL,
    KeyNpcNumber1    INT          NULL,
    KeyNpcNumber2    INT          NULL,
    KeyNpcNumber3    INT          NULL,
    KeyNpcNumber4    INT          NULL,
    KeyNpcNumber5    INT          NULL,
    EndNPCNumber     INT          NOT NULL,
    Solution1        INT          NULL,
    Solution2        INT          NULL,
    Solution3        INT          NULL,
    Solution4        INT          NULL,
    NextIndex        INT          NULL,
    CONSTRAINT PK_Quests PRIMARY KEY CLUSTERED (QuestId),
    CONSTRAINT FK_Quests_Level FOREIGN KEY (Level) REFERENCES world.Levels (Level),
    CONSTRAINT FK_Quests_SummonZone FOREIGN KEY (SummonZoneNumber) REFERENCES world.Zones (ZoneNumber),
    CONSTRAINT FK_Quests_StartNpc FOREIGN KEY (StartNPCNumber) REFERENCES world.Npcs (NpcId),
    CONSTRAINT FK_Quests_EndNpc FOREIGN KEY (EndNPCNumber) REFERENCES world.Npcs (NpcId),
    CONSTRAINT FK_Quests_KeyNpc1 FOREIGN KEY (KeyNpcNumber1) REFERENCES world.Npcs (NpcId),
    CONSTRAINT FK_Quests_KeyNpc2 FOREIGN KEY (KeyNpcNumber2) REFERENCES world.Npcs (NpcId),
    CONSTRAINT FK_Quests_KeyNpc3 FOREIGN KEY (KeyNpcNumber3) REFERENCES world.Npcs (NpcId),
    CONSTRAINT FK_Quests_KeyNpc4 FOREIGN KEY (KeyNpcNumber4) REFERENCES world.Npcs (NpcId),
    CONSTRAINT FK_Quests_KeyNpc5 FOREIGN KEY (KeyNpcNumber5) REFERENCES world.Npcs (NpcId),
    CONSTRAINT FK_Quests_NextQuest FOREIGN KEY (NextIndex) REFERENCES world.Quests (QuestId),
    CONSTRAINT CK_Quests_Category CHECK (Category BETWEEN 1 AND 4),
    CONSTRAINT CK_Quests_Type CHECK (Type BETWEEN 1 AND 2),
    CONSTRAINT CK_Quests_Sort CHECK (Sort BETWEEN 1 AND 8),
    CONSTRAINT CK_Quests_Step CHECK (Step BETWEEN 1 AND 1000)
);
