CREATE TABLE world.SkillGrades
(
    SkillId          INT      NOT NULL,
    GradeIndex       TINYINT  NOT NULL,
    ManaUse          SMALLINT NOT NULL,
    RecoverInfo1     TINYINT  NOT NULL,
    RecoverInfo2     TINYINT  NOT NULL,
    StunAttack       TINYINT  NOT NULL,
    StunDefense      TINYINT  NOT NULL,
    FastRunSpeed     SMALLINT NOT NULL,
    AttackInfo1      SMALLINT NOT NULL,
    AttackInfo2      TINYINT  NOT NULL,
    AttackInfo3      TINYINT  NOT NULL, 
    RunTime          SMALLINT NOT NULL,
    ChargingDamageUp TINYINT  NOT NULL,
    AttackPowerUp    TINYINT  NOT NULL,
    DefensePowerUp   TINYINT  NOT NULL,
    AttackSuccessUp  TINYINT  NOT NULL,
    AttackBlockUp    TINYINT  NOT NULL,
    ElementAttackUp  TINYINT  NOT NULL,
    ElementDefenseUp TINYINT  NOT NULL, 
    AttackSpeedUp    TINYINT  NOT NULL,
    RunSpeedUp       TINYINT  NOT NULL,
    ShieldLifeUp     TINYINT  NOT NULL,
    LuckUp           TINYINT  NOT NULL,
    CriticalUp       TINYINT  NOT NULL,
    ReturnSuccessUp  TINYINT  NOT NULL,
    StunDefenseUp    TINYINT  NOT NULL,
    DestroySuccessUp TINYINT  NOT NULL,
    CONSTRAINT PK_SkillGrades PRIMARY KEY CLUSTERED (SkillId, GradeIndex),
    CONSTRAINT FK_SkillGrades_Skills FOREIGN KEY (SkillId) REFERENCES world.Skills (SkillId),
    CONSTRAINT CK_SkillGrades_GradeIndex CHECK (GradeIndex BETWEEN 0 AND 1),
    CONSTRAINT CK_SkillGrades_ManaUse CHECK (ManaUse BETWEEN 0 AND 10000),
    CONSTRAINT CK_SkillGrades_RecoverInfo1 CHECK (RecoverInfo1 BETWEEN 0 AND 10000),
    CONSTRAINT CK_SkillGrades_RecoverInfo2 CHECK (RecoverInfo2 BETWEEN 0 AND 10000),
    CONSTRAINT CK_SkillGrades_StunAttack CHECK (StunAttack BETWEEN 0 AND 100),
    CONSTRAINT CK_SkillGrades_StunDefense CHECK (StunDefense BETWEEN 0 AND 100),
    CONSTRAINT CK_SkillGrades_FastRunSpeed CHECK (FastRunSpeed BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_AttackInfo1 CHECK (AttackInfo1 BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_AttackInfo2 CHECK (AttackInfo2 BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_AttackInfo3 CHECK (AttackInfo3 BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_RunTime CHECK (RunTime BETWEEN 0 AND 10000),
    CONSTRAINT CK_SkillGrades_ChargingDamageUp CHECK (ChargingDamageUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_AttackPowerUp CHECK (AttackPowerUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_DefensePowerUp CHECK (DefensePowerUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_AttackSuccessUp CHECK (AttackSuccessUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_AttackBlockUp CHECK (AttackBlockUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_ElementAttackUp CHECK (ElementAttackUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_ElementDefenseUp CHECK (ElementDefenseUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_AttackSpeedUp CHECK (AttackSpeedUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_RunSpeedUp CHECK (RunSpeedUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_ShieldLifeUp CHECK (ShieldLifeUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_LuckUp CHECK (LuckUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_CriticalUp CHECK (CriticalUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_ReturnSuccessUp CHECK (ReturnSuccessUp BETWEEN 0 AND 10000),
    CONSTRAINT CK_SkillGrades_StunDefenseUp CHECK (StunDefenseUp BETWEEN 0 AND 1000),
    CONSTRAINT CK_SkillGrades_DestroySuccessUp CHECK (DestroySuccessUp BETWEEN 0 AND 10000)
);
