using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Diagnostics;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Scanning;
using Fenrir.Generators.Analysis.Support;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Fenrir.Generators.Dispatch;

[Generator(LanguageNames.CSharp)]
public sealed class HandlerDispatchIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) =>
                    node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, _) => GetHandlerModels(ctx))
            .SelectMany(static (models, _) => models)
            .WithTrackingName(TrackingNames.HandlerModels)
            .Collect();

        var assemblyName = context.CompilationProvider
            .Select(static (compilation, _) => compilation.AssemblyName)
            .WithTrackingName(TrackingNames.AssemblyName);

        context.RegisterSourceOutput(
            handlers.Combine(assemblyName),
            static (spc, pair) => Emit(spc, pair.Left, pair.Right));
    }

    private static ImmutableArray<HandlerModel> GetHandlerModels(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol typeSymbol ||
            typeSymbol.IsAbstract || typeSymbol.TypeKind == TypeKind.Interface)
            return ImmutableArray<HandlerModel>.Empty;

        ImmutableArray<HandlerModel>.Builder? builder = null;

        foreach (var candidateInterface in typeSymbol.AllInterfaces)
        {
            if (candidateInterface.TypeArguments.Length != 1)
                continue;

            var isInline = SymbolNameHelpers.IsClosedGenericOf(candidateInterface, WellKnownNames.IInlinePacketHandler);
            var isAsync = !isInline &&
                          SymbolNameHelpers.IsClosedGenericOf(candidateInterface, WellKnownNames.IAsyncPacketHandler);

            if (!isInline && !isAsync)
                continue;

            if (candidateInterface.TypeArguments[0] is not INamedTypeSymbol packetType)
                continue;

            var packetAttribute = packetType.GetAttributes().Find(WellKnownNames.FenrirPacketAttribute);
            if (packetAttribute is null)
                continue;

            var server = (FenrirServer)packetAttribute.GetCtorInt32(0);
            var opcode = (byte)packetAttribute.GetCtorInt32(2);

            builder ??= ImmutableArray.CreateBuilder<HandlerModel>();
            builder.Add(new HandlerModel
            {
                HandlerTypeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                PacketTypeFullName = packetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                Server = server,
                Opcode = opcode,
                IsAsync = isAsync,
                Location = LocationInfo.From(typeSymbol.Locations.FirstOrDefault())
            });
        }

        return builder?.ToImmutable() ?? ImmutableArray<HandlerModel>.Empty;
    }

    private static void Emit(
        SourceProductionContext context,
        ImmutableArray<HandlerModel> handlers,
        string? assemblyName)
    {
        if (handlers.IsEmpty)
            return;

        ReportCollisions(context, handlers);

        var server = handlers[0].Server;

        var servers = handlers.Select(h => h.Server).Distinct().OrderBy(s => s).ToImmutableArray();
        if (servers.Length > 1)
        {
            foreach (var stray in handlers.Where(h => h.Server != server))
                context.ReportDiagnostic(DiagnosticInfo.Create(
                    FenrirDiagnostics.MultipleHandlerServersInCompilation,
                    stray.Location,
                    assemblyName ?? "(unknown)",
                    string.Join(", ", servers),
                    server).ToDiagnostic());
            return;
        }

        var inline = Deduplicate(handlers.Where(h => !h.IsAsync));
        var async = Deduplicate(handlers.Where(h => h.IsAsync));

        var namespaceName = EmittedNames.NamespaceFor(assemblyName);
        var dispatcherName = EmittedNames.MessageDispatcher(server);
        var hubName = EmittedNames.PacketHandlerHub(server);

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {namespaceName};");
        writer.Line();
        writer.Line("/// <summary>");
        writer.Line(
            "/// Dispatch table generated from the IInlinePacketHandler{T}/IAsyncPacketHandler{T} discovered in");
        writer.Line(
            "/// this compilation. Empty (only a 'default' rejecting the opcode) until a handler is declared.");
        writer.Line(
            $"/// Handlers are resolved through <see cref=\"{hubName}.Services\"/> rather than constructed");
        writer.Line(
            "/// directly, so a handler may take constructor-injected dependencies (repositories, options, ...).");
        writer.Line("/// </summary>");
        writer.Line($"public static class {dispatcherName}");
        writer.OpenBrace();

        EmitInline(writer, inline, hubName);
        writer.Line();
        EmitAsync(writer, async, hubName);

        writer.CloseBrace();
        writer.Line();
        writer.Line(
            $"/// <summary>DI bridge for <see cref=\"{dispatcherName}\"/>: call <see cref=\"Initialize\"/> once, after the host's service provider is built and before accepting connections.</summary>");
        writer.Line($"public static class {hubName}");
        writer.OpenBrace();
        writer.Line("public static global::System.IServiceProvider? Services { get; private set; }");
        writer.Line();
        writer.Line("public static void Initialize(global::System.IServiceProvider serviceProvider)");
        writer.OpenBrace();
        writer.Line("Services = serviceProvider;");
        writer.CloseBrace();
        writer.CloseBrace();
        writer.Line();
        EmitRegistration(writer, handlers, server);

        context.AddSource("MessageDispatcher.g.cs", writer.ToString());
    }

    private static void EmitRegistration(
        IndentedWriter writer,
        ImmutableArray<HandlerModel> handlers,
        FenrirServer server)
    {
        var handlerTypes = handlers
            .Select(h => h.HandlerTypeFullName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToList();

        writer.Line(
            $"/// <summary>Registers every packet handler discovered in this compilation as a DI singleton (one per <see cref=\"{EmittedNames.MessageDispatcher(server)}\"/> dispatch entry).</summary>");
        writer.Line($"public static class {EmittedNames.HandlerRegistration(server)}");
        writer.OpenBrace();
        writer.Line(
            $"public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {EmittedNames.AddHandlersMethod(server)}(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        writer.OpenBrace();

        foreach (var handlerType in handlerTypes)
            writer.Line(
                $"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<{handlerType}>(services);");

        writer.Line("return services;");
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void ReportCollisions(SourceProductionContext context, ImmutableArray<HandlerModel> handlers)
    {
        var (_, diagnostics) = HandlerCollisionChecker.Check(handlers);

        foreach (var diagnostic in diagnostics)
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
    }

    private static ImmutableArray<HandlerModel> Deduplicate(IEnumerable<HandlerModel> handlers)
    {
        var seen = new HashSet<(FenrirServer, byte)>();
        var builder = ImmutableArray.CreateBuilder<HandlerModel>();

        foreach (var handler in handlers)
            if (seen.Add((handler.Server, handler.Opcode)))
                builder.Add(handler);

        return builder.ToImmutable();
    }

    private static ImmutableArray<HandlerModel> InEmissionOrder(ImmutableArray<HandlerModel> handlers)
    {
        return handlers.OrderBy(h => h.Server).ThenBy(h => h.Opcode).ToImmutableArray();
    }

    private static void EmitInline(IndentedWriter writer, ImmutableArray<HandlerModel> handlers, string hubName)
    {
        handlers = InEmissionOrder(handlers);

        writer.Line(
            $"public static bool TryHandleInline({WellKnownNames.FenrirServerEnum} server, byte opcode, global::System.ReadOnlySpan<byte> payload, {WellKnownNames.IPacketSession} session)");
        writer.OpenBrace();
        writer.Line("switch ((server, opcode))");
        writer.OpenBrace();

        foreach (var handler in handlers)
        {
            writer.Line($"case ({ServerLiteral(handler.Server)}, {handler.Opcode}):");
            writer.OpenBrace();
            writer.Line($"if (!{handler.PacketTypeFullName}.TryRead(payload, out var packet))");
            writer.OpenBrace();
            writer.Line("return false;");
            writer.CloseBrace();
            writer.Line(
                $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handler.HandlerTypeFullName}>({hubName}.Services!).Handle(in packet, session);");
            writer.Line("return true;");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("return false;");
        writer.CloseBrace();
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitAsync(IndentedWriter writer, ImmutableArray<HandlerModel> handlers, string hubName)
    {
        handlers = InEmissionOrder(handlers);

        writer.Line(
            $"public static async global::System.Threading.Tasks.ValueTask<bool> TryHandleAsync({WellKnownNames.FenrirServerEnum} server, byte opcode, global::System.ReadOnlyMemory<byte> payload, {WellKnownNames.IPacketSession} session, global::System.Threading.CancellationToken cancellationToken)");
        writer.OpenBrace();
        writer.Line("switch ((server, opcode))");
        writer.OpenBrace();

        foreach (var handler in handlers)
        {
            writer.Line($"case ({ServerLiteral(handler.Server)}, {handler.Opcode}):");
            writer.OpenBrace();
            writer.Line($"if (!{handler.PacketTypeFullName}.TryRead(payload.Span, out var packet))");
            writer.OpenBrace();
            writer.Line("return false;");
            writer.CloseBrace();
            writer.Line(
                $"await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handler.HandlerTypeFullName}>({hubName}.Services!).HandleAsync(packet, session, cancellationToken);");
            writer.Line("return true;");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("return false;");
        writer.CloseBrace();
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static string ServerLiteral(FenrirServer server)
    {
        return server switch
        {
            FenrirServer.Login => $"{WellKnownNames.FenrirServerEnum}.Login",
            FenrirServer.Zone => $"{WellKnownNames.FenrirServerEnum}.Zone",
            _ => throw new ArgumentOutOfRangeException(nameof(server), server, null)
        };
    }
}
