using System.Collections.Immutable;
using Fenrir.Application.Game.Domain.Quests;
using Fenrir.Domain.Game.Stats;

namespace Fenrir.Application.Game.Domain.Tribes;

public readonly record struct TribeProgressZoneCommand(
    int CharacterId,
    int? ContributionPoints = null,
    byte? TribeRole = null,
    int? Title = null,
    int? Halo = null,
    int? ProtectForHalo = null,
    bool? UseOrnament = null,
    int? BonusItemLevel = null,
    bool? BonusItemValue = null,
    int? StatVit = null,
    int? StatStr = null,
    int? StatInt = null,
    int? StatDex = null,
    int? StatPoints = null,
    int? Life = null,
    int? Mana = null,
    int? MaxLife = null,
    int? MaxMana = null,
    EffectiveStats? UpdatedStats = null,
    ImmutableArray<TribeGroundItemDrop> DropItems = default,
    int? TribeNotifyScrollCount = null,
    int? Exp2 = null,
    int? RebirthCount = null,
    bool RebirthBroadcast = false,
    int? Zone241Time = null,
    int? LodRounds = null,
    int? ProtectForRefine = null,
    int? ProtectForDestroy = null,
    int? ProtectForCostume = null,
    int? ProtectForDestroy2 = null,
    int? ImproveItemValue = null,
    int? AddItemValue = null,
    int? HighItemValue = null,
    int? DropItemTime = null,
    int? TaiyanKeyTimer = null,
    int? EliteDungeonTime = null,
    int? DungeonKeyTime = null,
    int? IvyHallTicketTime = null,
    int? ScrollOfSeekersTime = null,
    int? TeacherPoint = null,
    int? PetGrowth = null,
    byte? PetActivity = null,
    bool PetGrowStepBroadcast = false,
    int? PlayTimeEvent = null,
    int? EatLifePotion = null,
    int? EatManaPotion = null,
    int? EatStrPotion = null,
    int? EatDexPotion = null,
    int? EatElePotion = null,
    bool FullActionRebroadcast = false,
    int? PetExpX2Time = null,
    byte? Tribe = null,
    QuestProgress? QuestProgress = null,
    int? TribeFourReturnAllowance = null,
    long? StoreMoney = null,
    int? SkillPoints = null,
    int? GmSummonMonsterTemplateId = null,
    int? VisibleState = null,
    int? SpecialState = null,
    byte? PreviousTribe = null,
    (float X, float Y, float Z)? TeleportTo = null,
    bool NeighborActionBroadcast = false,
    bool ResetAfkTick = false,
    short? Level = null,
    short? Level2 = null,
    long? Experience = null,
    int? M15PetLuckyBoxPity = null,
    int? BigMoneyDelta = null,
    TaskCompletionSource? Applied = null);

public readonly record struct TribeGroundItemDrop(int ItemId, int Quantity, int DropSort = 0);
