CREATE SCHEMA auth AUTHORIZATION dbo;
GO

CREATE SCHEMA game AUTHORIZATION dbo;
GO

CREATE SCHEMA runtime AUTHORIZATION dbo;
GO

CREATE SCHEMA admin AUTHORIZATION dbo;
GO

CREATE SCHEMA world AUTHORIZATION dbo;
GO
