using System.Globalization;
using System.Text;
using Fenrir.Tools.DbMigrator.Legacy.Readers;
using Fenrir.Tools.DbMigrator.Legacy.Records;

namespace Fenrir.Tools.DbMigrator.Legacy.Seeding;

public sealed record QuestSeedStats(
    int TotalRawRecords,
    int PaddingRecordsExcluded,
    int QuestRowCount,
    int QuestRewardRowCount,
    int QuestSpeechRowCount);

public static class QuestSeedGenerator
{
    private const int RewardTypeNone = 1;
    private const int RewardTypeMoney = 2;
    private const int RewardTypeKillOtherTribeCount = 3;
    private const int RewardTypeExperience = 4;
    private const int RewardTypeTeacherPoint = 5;

    private const int RewardTypeItem = 6;

    private const byte SpeechStart = 0;
    private const byte SpeechHurry = 1;
    private const byte SpeechProcess1 = 2;
    private const byte SpeechProcess2 = 3;
    private const byte SpeechProcess3 = 4;
    private const byte SpeechProcess4 = 5;
    private const byte SpeechProcess5 = 6;
    private const byte SpeechSuccess = 7;
    private const byte SpeechFailure = 8;
    private const byte SpeechCall = 9;

    private const int MaxRowsPerInsert = 500;

    public static QuestSeedStats Generate(string dataDir, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        var all = QuestReader.ReadAll(dataDir);
        var quests = all.Where(q => !string.IsNullOrEmpty(q.Subject)).ToList();
        var includedIds = new HashSet<int>(quests.Select(q => q.Index));

        var questRows = new List<string>(quests.Count);
        var rewardRows = new List<string>(quests.Count * 3);
        var speechRows = new List<string>(quests.Count * 10 * 15);

        foreach (var q in quests)
        {
            questRows.Add(BuildQuestRow(q, includedIds));

            for (var slot = 0; slot < 3; slot++)
            {
                var type = q.Reward[slot][0];
                if (type == RewardTypeNone) continue;
                var value = q.Reward[slot][1];
                var itemId = type == RewardTypeItem ? value.ToString(CultureInfo.InvariantCulture) : "NULL";
                var amount = type == RewardTypeItem ? "NULL" : value.ToString(CultureInfo.InvariantCulture);
                rewardRows.Add($"({q.Index}, {slot}, {type}, {itemId}, {amount})");
            }

            AppendSpeechRows(speechRows, q.Index, SpeechStart, q.StartSpeech, q.StartSpeechColor);
            AppendSpeechRows(speechRows, q.Index, SpeechHurry, q.HurrySpeech, q.HurrySpeechColor);
            AppendSpeechRows(speechRows, q.Index, SpeechProcess1, q.ProcessSpeech1, q.ProcessSpeech1Color);
            AppendSpeechRows(speechRows, q.Index, SpeechProcess2, q.ProcessSpeech2, q.ProcessSpeech2Color);
            AppendSpeechRows(speechRows, q.Index, SpeechProcess3, q.ProcessSpeech3, q.ProcessSpeech3Color);
            AppendSpeechRows(speechRows, q.Index, SpeechProcess4, q.ProcessSpeech4, q.ProcessSpeech4Color);
            AppendSpeechRows(speechRows, q.Index, SpeechProcess5, q.ProcessSpeech5, q.ProcessSpeech5Color);
            AppendSpeechRows(speechRows, q.Index, SpeechSuccess, q.SuccessSpeech, q.SuccessSpeechColor);
            AppendSpeechRows(speechRows, q.Index, SpeechFailure, q.FailureSpeech, q.FailureSpeechColor);
            AppendSpeechRows(speechRows, q.Index, SpeechCall, q.CallSpeech, q.CallSpeechColor);
        }

        var questsSb = new StringBuilder();
        questsSb.AppendLine("-- Generated by Fenrir.Tools.DbMigrator.Legacy.Seeding.QuestSeedGenerator from");
        questsSb.AppendLine("-- 005_00006.IMG (real legacy DATA directory) -- do not hand-edit, regenerate instead.");
        questsSb.AppendLine($"-- Row count at generation time: world.Quests={quests.Count} (of {all.Count} raw " +
                            $"array slots, {all.Count - quests.Count} unused-padding slots excluded).");
        questsSb.AppendLine();
        WriteGuardedInsertBlock(questsSb, "world.Quests",
            "QuestId, Subject, Category, Step, Level, Type, Sort, " +
            "SummonZoneNumber, SummonPosX, SummonPosY, SummonPosZ, " +
            "StartNPCNumber, KeyNpcNumber1, KeyNpcNumber2, KeyNpcNumber3, KeyNpcNumber4, KeyNpcNumber5, EndNPCNumber, " +
            "Solution1, Solution2, Solution3, Solution4, NextIndex",
            questRows,
            int.MaxValue);
        File.WriteAllText(Path.Combine(outputDir, "022_quests.sql"), questsSb.ToString());

        var rewardsSb = new StringBuilder();
        rewardsSb.AppendLine("-- Generated by Fenrir.Tools.DbMigrator.Legacy.Seeding.QuestSeedGenerator from");
        rewardsSb.AppendLine("-- 005_00006.IMG (real legacy DATA directory) -- do not hand-edit, regenerate instead.");
        rewardsSb.AppendLine($"-- Row count at generation time: world.QuestRewards={rewardRows.Count} (of a " +
                             $"theoretical {quests.Count * 3} = {quests.Count} quests x 3 slots max; the rest " +
                             "are RewardType=1 \"none\" sentinel slots, intentionally not stored).");
        rewardsSb.AppendLine();
        WriteGuardedInsertBlock(rewardsSb, "world.QuestRewards", "QuestId, SlotIndex, RewardType, ItemId, Amount",
            rewardRows, MaxRowsPerInsert);
        File.WriteAllText(Path.Combine(outputDir, "023_quest_rewards.sql"), rewardsSb.ToString());

        var speechesSb = new StringBuilder();
        speechesSb.AppendLine("-- Generated by Fenrir.Tools.DbMigrator.Legacy.Seeding.QuestSeedGenerator from");
        speechesSb.AppendLine("-- 005_00006.IMG (real legacy DATA directory) -- do not hand-edit, regenerate instead.");
        speechesSb.AppendLine($"-- Row count at generation time: world.QuestSpeeches={speechRows.Count} (theoretical " +
                              "max 1000 quest slots x 10 speech blocks x 15 lines = 150,000; even restricted to " +
                              $"just the {quests.Count} real quests it would be {quests.Count * 10 * 15} -- sparse " +
                              "per-line normalization is what actually keeps this table small).");
        speechesSb.AppendLine();
        WriteGuardedInsertBlock(speechesSb, "world.QuestSpeeches", "QuestId, SpeechKind, LineIndex, Text, Color",
            speechRows, MaxRowsPerInsert);
        File.WriteAllText(Path.Combine(outputDir, "024_quest_speeches.sql"), speechesSb.ToString());

        return new QuestSeedStats(all.Count, all.Count - quests.Count, quests.Count, rewardRows.Count,
            speechRows.Count);
    }

    private static string BuildQuestRow(QuestRecord q, HashSet<int> includedIds)
    {
        var nextIndex = q.NextIndex == 0 || !includedIds.Contains(q.NextIndex)
            ? "NULL"
            : q.NextIndex.ToString(CultureInfo.InvariantCulture);

        var summonZone = q.SummonInfo[0] == 0 ? "NULL" : q.SummonInfo[0].ToString(CultureInfo.InvariantCulture);
        var summonX = q.SummonInfo[1] == 0 ? "NULL" : q.SummonInfo[1].ToString(CultureInfo.InvariantCulture);
        var summonY = q.SummonInfo[2] == 0 ? "NULL" : q.SummonInfo[2].ToString(CultureInfo.InvariantCulture);
        var summonZ = q.SummonInfo[3] == 0 ? "NULL" : q.SummonInfo[3].ToString(CultureInfo.InvariantCulture);

        var keyNpc = q.KeyNPCNumber.Select(NullIfZero).ToArray();
        var solution = q.Solution.Select(NullIfZero).ToArray();

        return "(" + string.Join(", ", new[]
        {
            q.Index.ToString(CultureInfo.InvariantCulture),
            SqlString(q.Subject),
            q.Category.ToString(CultureInfo.InvariantCulture),
            q.Step.ToString(CultureInfo.InvariantCulture),
            q.Level.ToString(CultureInfo.InvariantCulture),
            q.Type.ToString(CultureInfo.InvariantCulture),
            q.Sort.ToString(CultureInfo.InvariantCulture),
            summonZone, summonX, summonY, summonZ,
            q.StartNPCNumber.ToString(CultureInfo.InvariantCulture),
            keyNpc[0], keyNpc[1], keyNpc[2], keyNpc[3], keyNpc[4],
            q.EndNPCNumber.ToString(CultureInfo.InvariantCulture),
            solution[0], solution[1], solution[2], solution[3],
            nextIndex
        }) + ")";
    }

    private static void AppendSpeechRows(List<string> rows, int questId, byte speechKind, IReadOnlyList<string> lines,
        IReadOnlyList<int> colors)
    {
        for (var i = 0; i < lines.Count; i++)
        {
            if (string.IsNullOrEmpty(lines[i])) continue;
            rows.Add($"({questId}, {speechKind}, {i}, {SqlString(lines[i])}, {colors[i]})");
        }
    }

    private static string NullIfZero(int value)
    {
        return value == 0 ? "NULL" : value.ToString(CultureInfo.InvariantCulture);
    }

    private static string SqlString(string value)
    {
        return "N'" + value.Replace("'", "''") + "'";
    }

    private static void WriteGuardedInsertBlock(StringBuilder sb, string table, string columns, List<string> rows,
        int maxRowsPerInsert)
    {
        sb.AppendLine($"IF NOT EXISTS (SELECT 1 FROM {table})");
        sb.AppendLine("BEGIN");
        for (var offset = 0; offset < rows.Count; offset += maxRowsPerInsert)
        {
            var chunk = rows.Skip(offset).Take(maxRowsPerInsert).ToList();
            sb.AppendLine($"    INSERT INTO {table} ({columns}) VALUES");
            for (var i = 0; i < chunk.Count; i++)
            {
                var suffix = i == chunk.Count - 1 ? ";" : ",";
                sb.AppendLine($"    {chunk[i]}{suffix}");
            }
        }

        sb.AppendLine("END;");
        sb.AppendLine();
    }
}
