<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Fenrir.GameServer-76cf51b5-0a11-4b95-8b3a-829642054a85</UserSecretsId>
    <FenrirExecutable>true</FenrirExecutable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Abstractions\Fenrir.Network.Abstractions.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization.Wire\Fenrir.Network.Serialization.Wire.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization.Shared\Fenrir.Network.Serialization.Shared.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization.Zone\Fenrir.Network.Serialization.Zone.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Transport\Fenrir.Network.Transport.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Framing\Fenrir.Network.Framing.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Dispatch\Fenrir.Network.Dispatch.csproj"/>
    <ProjectReference Include="..\..\Infrastructure\Fenrir.Data\Fenrir.Data.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Domain\Fenrir.Application.Game.Domain.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.GameData\Fenrir.Application.Game.GameData.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Services\Fenrir.Application.Game.Services.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Handlers\Fenrir.Application.Game.Handlers.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Hosting\Fenrir.Application.Game.Hosting.csproj"/>
    <ProjectReference Include="..\..\Orchestration\Fenrir.ServiceDefaults\Fenrir.ServiceDefaults.csproj"/>
  </ItemGroup>

</Project>
