<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fenrir.Core\Fenrir.Core.csproj"/>
    <ProjectReference Include="..\Fenrir.Data.Abstractions\Fenrir.Data.Abstractions.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Fenrir.Data.Abstractions.Accounts"/>
    <Using Include="Fenrir.Data.Abstractions.Admin"/>
    <Using Include="Fenrir.Data.Abstractions.Characters"/>
    <Using Include="Fenrir.Data.Abstractions.Commerce"/>
    <Using Include="Fenrir.Data.Abstractions.Guilds"/>
    <Using Include="Fenrir.Data.Abstractions.Progression"/>
    <Using Include="Fenrir.Data.Abstractions.Runtime"/>
    <Using Include="Fenrir.Data.Abstractions.Security"/>
    <Using Include="Fenrir.Data.Abstractions.Social"/>
    <Using Include="Fenrir.Data.Abstractions.Tribes"/>
    <Using Include="Fenrir.Data.Abstractions.World"/>
  </ItemGroup>
</Project>
