using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Fenrir.Generators.Dispatch;

/// <summary>
///     Discovers handlers in the current compilation and emits <c>MessageDispatcher</c>/<c>PacketHandlerHub</c>.
///     Not wired on Fenrir.Contracts itself: two assemblies both emitting the same dispatch type would collide.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class HandlerDispatchIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) =>
                    node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, _) => GetHandlerModels(ctx))
            .SelectMany(static (models, _) => models)
            .Collect();

        context.RegisterSourceOutput(handlers, static (spc, models) => Emit(spc, models));
    }

    private static ImmutableArray<HandlerModel> GetHandlerModels(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol typeSymbol ||
            typeSymbol.IsAbstract || typeSymbol.TypeKind == TypeKind.Interface)
            return ImmutableArray<HandlerModel>.Empty;

        ImmutableArray<HandlerModel>.Builder? builder = null;

        foreach (var candidateInterface in typeSymbol.AllInterfaces)
        {
            if (candidateInterface.TypeArguments.Length != 1)
                continue;

            var isInline = SymbolNameHelpers.IsClosedGenericOf(candidateInterface, WellKnownNames.IInlinePacketHandler);
            var isAsync = !isInline &&
                          SymbolNameHelpers.IsClosedGenericOf(candidateInterface, WellKnownNames.IAsyncPacketHandler);

            if (!isInline && !isAsync)
                continue;

            if (candidateInterface.TypeArguments[0] is not INamedTypeSymbol packetType)
                continue;

            var packetAttribute = packetType.GetAttributes().Find(WellKnownNames.FenrirPacketAttribute);
            if (packetAttribute is null)
                continue;

            var server = (FenrirServer)packetAttribute.GetCtorInt32(0);
            var opcode = (byte)packetAttribute.GetCtorInt32(2);

            builder ??= ImmutableArray.CreateBuilder<HandlerModel>();
            builder.Add(new HandlerModel
            {
                HandlerTypeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                PacketTypeFullName = packetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                Server = server,
                Opcode = opcode,
                IsAsync = isAsync
            });
        }

        return builder?.ToImmutable() ?? ImmutableArray<HandlerModel>.Empty;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<HandlerModel> handlers)
    {
        var inline = Deduplicate(handlers.Where(h => !h.IsAsync));
        var async = Deduplicate(handlers.Where(h => h.IsAsync));

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("namespace Fenrir.Network.Dispatch;");
        writer.Line();
        writer.Line("/// <summary>");
        writer.Line(
            "/// Dispatch table generated from the IInlinePacketHandler{T}/IAsyncPacketHandler{T} discovered in");
        writer.Line(
            "/// this compilation. Empty (only a 'default' rejecting the opcode) until a handler is declared.");
        writer.Line(
            "/// Handlers are resolved through <see cref=\"PacketHandlerHub.Services\"/> rather than constructed");
        writer.Line(
            "/// directly, so a handler may take constructor-injected dependencies (repositories, options, ...).");
        writer.Line("/// </summary>");
        writer.Line("public static class MessageDispatcher");
        writer.OpenBrace();

        EmitInline(writer, inline);
        writer.Line();
        EmitAsync(writer, async);

        writer.CloseBrace();
        writer.Line();
        writer.Line(
            "/// <summary>DI bridge for <see cref=\"MessageDispatcher\"/>: call <see cref=\"Initialize\"/> once, after the host's service provider is built and before accepting connections.</summary>");
        writer.Line("public static class PacketHandlerHub");
        writer.OpenBrace();
        writer.Line("public static global::System.IServiceProvider? Services { get; private set; }");
        writer.Line();
        writer.Line("public static void Initialize(global::System.IServiceProvider serviceProvider)");
        writer.OpenBrace();
        writer.Line("Services = serviceProvider;");
        writer.CloseBrace();
        writer.CloseBrace();
        writer.Line();
        EmitRegistration(writer, handlers);

        context.AddSource("MessageDispatcher.g.cs", writer.ToString());
    }

    /// <summary>
    ///     Registers every dispatched handler as a DI singleton from the same discovery pass, so dispatch and
    ///     registration can't drift.
    /// </summary>
    private static void EmitRegistration(IndentedWriter writer, ImmutableArray<HandlerModel> handlers)
    {
        var handlerTypes = handlers
            .Select(h => h.HandlerTypeFullName)
            .Distinct()
            .OrderBy(name => name)
            .ToList();

        writer.Line(
            "/// <summary>Registers every packet handler discovered in this compilation as a DI singleton (one per <see cref=\"MessageDispatcher\"/> dispatch entry).</summary>");
        writer.Line("public static class GeneratedHandlerRegistration");
        writer.OpenBrace();
        writer.Line(
            "public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedPacketHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        writer.OpenBrace();

        foreach (var handlerType in handlerTypes)
            writer.Line(
                $"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<{handlerType}>(services);");

        writer.Line("return services;");
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static ImmutableArray<HandlerModel> Deduplicate(IEnumerable<HandlerModel> handlers)
    {
        var seen = new HashSet<(FenrirServer, byte)>();
        var builder = ImmutableArray.CreateBuilder<HandlerModel>();

        foreach (var handler in handlers)
            if (seen.Add((handler.Server, handler.Opcode)))
                builder.Add(handler);

        return builder.ToImmutable();
    }

    private static void EmitInline(IndentedWriter writer, ImmutableArray<HandlerModel> handlers)
    {
        writer.Line(
            "public static bool TryHandleInline(global::Fenrir.Network.Abstractions.FenrirServer server, byte opcode, global::System.ReadOnlySpan<byte> payload, global::Fenrir.Network.Abstractions.IPacketSession session)");
        writer.OpenBrace();
        writer.Line("switch ((server, opcode))");
        writer.OpenBrace();

        foreach (var handler in handlers)
        {
            writer.Line($"case ({ServerLiteral(handler.Server)}, {handler.Opcode}):");
            writer.OpenBrace();
            writer.Line($"if (!{handler.PacketTypeFullName}.TryRead(payload, out var packet))");
            writer.OpenBrace();
            writer.Line("return false;");
            writer.CloseBrace();
            writer.Line(
                $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handler.HandlerTypeFullName}>(PacketHandlerHub.Services!).Handle(in packet, session);");
            writer.Line("return true;");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("return false;");
        writer.CloseBrace();
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitAsync(IndentedWriter writer, ImmutableArray<HandlerModel> handlers)
    {
        writer.Line(
            "public static async global::System.Threading.Tasks.ValueTask<bool> TryHandleAsync(global::Fenrir.Network.Abstractions.FenrirServer server, byte opcode, global::System.ReadOnlyMemory<byte> payload, global::Fenrir.Network.Abstractions.IPacketSession session, global::System.Threading.CancellationToken cancellationToken)");
        writer.OpenBrace();
        writer.Line("switch ((server, opcode))");
        writer.OpenBrace();

        foreach (var handler in handlers)
        {
            writer.Line($"case ({ServerLiteral(handler.Server)}, {handler.Opcode}):");
            writer.OpenBrace();
            writer.Line($"if (!{handler.PacketTypeFullName}.TryRead(payload.Span, out var packet))");
            writer.OpenBrace();
            writer.Line("return false;");
            writer.CloseBrace();
            writer.Line(
                $"await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handler.HandlerTypeFullName}>(PacketHandlerHub.Services!).HandleAsync(packet, session, cancellationToken);");
            writer.Line("return true;");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("return false;");
        writer.CloseBrace();
        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static string ServerLiteral(FenrirServer server)
    {
        return server == FenrirServer.Login
            ? "global::Fenrir.Network.Abstractions.FenrirServer.Login"
            : "global::Fenrir.Network.Abstractions.FenrirServer.Zone";
    }
}
