<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <FenrirExecutable>true</FenrirExecutable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient"/>
    <PackageReference Include="CaeriusNet"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\3_Infrastructure\Fenrir.Data\Fenrir.Data.csproj"/>
    <ProjectReference Include="..\..\3_Infrastructure\Fenrir.Observability\Fenrir.Observability.csproj"/>
    <ProjectReference Include="..\..\0_Orchestration\Fenrir.ServiceDefaults\Fenrir.ServiceDefaults.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Database\**\*.*" CopyToOutputDirectory="PreserveNewest" LinkBase="Database"/>
  </ItemGroup>

</Project>
