<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Login.Domain\Fenrir.Application.Login.Domain.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Login.Abstractions\Fenrir.Application.Login.Abstractions.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Login.Services\Fenrir.Application.Login.Services.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Login.Handlers\Fenrir.Application.Login.Handlers.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Login.Hosting\Fenrir.Application.Login.Hosting.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Abstractions\Fenrir.Network.Abstractions.csproj"/>
  </ItemGroup>

</Project>
