<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Dispatch\Fenrir.Network.Dispatch.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Dispatch.Login\Fenrir.Network.Dispatch.Login.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Dispatch.Zone\Fenrir.Network.Dispatch.Zone.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization.Wire\Fenrir.Network.Serialization.Wire.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization.Shared\Fenrir.Network.Serialization.Shared.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization.Login\Fenrir.Network.Serialization.Login.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization.Zone\Fenrir.Network.Serialization.Zone.csproj"/>
  </ItemGroup>

</Project>