CREATE OR ALTER PROCEDURE world.usp_Monster_GetAll
AS
BEGIN
    SET
        NOCOUNT ON;

    SELECT m.MonsterId,
           m.Name,
           m.ChatLine1,
           m.ChatLine2,
           m.Type,
           m.SpecialType,
           m.DamageType,
           m.DataSortNumber,
           m.Size1,
           m.Size2,
           m.Size3,
           m.Size4,
           m.SizeCategory,
           m.CheckCollision,
           m.TotalHitNum,
           m.TotalSkillHitNum,
           m.ItemLevel,
           m.MartialItemLevel,
           m.RealLevel,
           m.MartialRealLevel,
           m.GeneralExperience,
           m.PatExperience,
           m.Life,
           m.AttackType,
           m.RadiusInfo1,
           m.RadiusInfo2,
           m.WalkSpeed,
           m.RunSpeed,
           m.DeathSpeed,
           m.AttackPower,
           m.DefensePower,
           m.AttackSuccess,
           m.AttackBlock,
           m.ElementAttackPower,
           m.ElementDefensePower,
           m.Critical,
           m.FollowInfo1,
           m.FollowInfo2,
           m.SummonTime1,
           m.SummonTime2,
           ISNULL(f.FrameInfo1, 1)     AS FrameInfo1,
           ISNULL(f.FrameInfo2, 1)     AS FrameInfo2,
           ISNULL(f.FrameInfo3, 1)     AS FrameInfo3,
           ISNULL(f.FrameInfo4, 1)     AS FrameInfo4,
           ISNULL(f.FrameInfo5, 1)     AS FrameInfo5,
           ISNULL(f.FrameInfo6, 1)     AS FrameInfo6,
           ISNULL(f.HitFrame1, 0)      AS HitFrame1,
           ISNULL(f.HitFrame2, 0)      AS HitFrame2,
           ISNULL(f.HitFrame3, 0)      AS HitFrame3,
           ISNULL(f.SkillHitFrame1, 0) AS SkillHitFrame1,
           ISNULL(f.SkillHitFrame2, 0) AS SkillHitFrame2,
           ISNULL(f.SkillHitFrame3, 0) AS SkillHitFrame3,
           ISNULL(f.BulletInfo1, 1)    AS BulletInfo1,
           ISNULL(f.BulletInfo2, 1)    AS BulletInfo2
    FROM world.Monsters AS m
             LEFT JOIN world.MonsterAnimationFrames AS f ON f.MonsterId = m.MonsterId
    ORDER BY m.MonsterId;
END;
