using System.Globalization;
using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

public sealed record GemSocketSeedStats(int RowCount);

public static class GemSocketSeedGenerator
{
    private const int MaxRowsPerInsert = 500;

        public static GemSocketSeedStats Generate(string dataDir, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        var sockets = SocketReader.ReadAll(dataDir);

        var rows = new List<string>(sockets.Count);
        for (var i = 0; i < sockets.Count; i++)
        {
            var s = sockets[i];
            var gemSocketId = i + 1;
            rows.Add(
                $"({gemSocketId.ToString(CultureInfo.InvariantCulture)}, {s.Type}, {s.Value01}, {s.Value02}, {s.Value03}, {s.Value04})");
        }

        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by Fenrir.Tools.LegacyDataImport.Legacy.Seeding.GemSocketSeedGenerator from");
        sb.AppendLine("-- 005_00010.IMG (real legacy DATA directory) -- do not hand-edit, regenerate instead.");
        sb.AppendLine(
            $"-- Row count at generation time: world.GemSockets={rows.Count} (all {sockets.Count} raw records, no sentinel/padding rows found).");
        sb.AppendLine();

        sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM world.GemSockets)");
        sb.AppendLine("BEGIN");
        for (var offset = 0; offset < rows.Count; offset += MaxRowsPerInsert)
        {
            var chunk = rows.Skip(offset).Take(MaxRowsPerInsert).ToList();
            sb.AppendLine(
                "    INSERT INTO world.GemSockets (GemSocketId, Type, Value01, Value02, Value03, Value04) VALUES");
            for (var i = 0; i < chunk.Count; i++)
            {
                var suffix = i == chunk.Count - 1 ? ";" : ",";
                sb.AppendLine($"    {chunk[i]}{suffix}");
            }
        }

        sb.AppendLine("END;");

        File.WriteAllText(Path.Combine(outputDir, "060_gem_sockets.sql"), sb.ToString());

        return new GemSocketSeedStats(rows.Count);
    }
}
