using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

public static class ItemBonusSkillSeedGenerator
{
    private const string BonusSkillColumns = "ItemId, SlotIndex, SkillId, Value";

    public static void Generate(string dataDir, string outputPath)
    {
        var items = ItemReader.ReadAll(dataDir).Where(i => i.Index != 0).OrderBy(i => i.Index).ToList();
        var bonusRows = items
            .SelectMany(i => i.BonusSkillInfo.Select((pair, slot) => (Item: i, Slot: slot, Pair: pair)))
            .Where(x => x.Pair[0] != 0 || x.Pair[1] != 0)
            .OrderBy(x => x.Item.Index).ThenBy(x => x.Slot)
            .Select(x => FormatBonusSkillRow(x.Item.Index, x.Slot, x.Pair))
            .ToList();

        var sb = new StringBuilder();
        sb.Append(
            "-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/ItemBonusSkillSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00002.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- One row per populated ItemRecord.BonusSkillInfo[8][2] slot, for real (Index != 0) items.\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.ItemBonusSkills)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.ItemBonusSkills", BonusSkillColumns, bonusRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"006_item_bonus_skills.sql: {bonusRows.Count} bonus-skill rows -> {outputPath}");
    }

    private static string FormatBonusSkillRow(int itemId, int slot, int[] pair)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(itemId),
            SqlSeedWriter.Number(slot),
            SqlSeedWriter.Number(SqlSeedWriter.ZeroToNull(pair[0])),
            SqlSeedWriter.Number(pair[1])
        });
    }
}
