using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;
using Fenrir.Tools.LegacyDataImport.Legacy.Records;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

/// <summary>
///     Generates <c>70_seed/world/080_items.sql</c> from <see cref="ItemReader.ReadAll" /> (005_00002.IMG,
///     post-runtime-patch), one row per item where Index != 0 (retired slots 89501-89562/99001 are the
///     legacy "deleted item" convention). GainSkillNumber's legacy "0 = no skill" sentinel becomes NULL.
/// </summary>
public static class ItemSeedGenerator
{
    private const string ItemColumns =
        "ItemId, Name, Description1, Description2, Description3, Type, Sort, DataNumber2D, DataNumber3D, " +
        "AddDataNumber3D, Level, MartialLevel, EquipInfo1, EquipInfo2, BuyCost, SellCost, BuyCost2, " +
        "LevelLimit, MartialLevelLimit, CheckMonsterDrop, CheckNpcSell, CheckNpcShop, CheckAvatarDrop, " +
        "CheckAvatarTrade, CheckAvatarShop, CheckImprove, CheckHighImprove, CheckHighItem, CheckLowItem, " +
        "CheckExchange, CheckSetItem, CheckDateItem, Strength, Dexterity, Vitality, Intelligent, Luck, " +
        "AttackPower, DefensePower, AttackSuccess, AttackBlock, ElementAttackPower, ElementDefensePower, " +
        "Critical, PotionType1, PotionType2, GainSkillNumber, LastAttackBonusInfo1, LastAttackBonusInfo2, " +
        "CapeInfo1, CapeInfo2, CapeInfo3";

    public static void Generate(string dataDir, string outputPath)
    {
        var items = ItemReader.ReadAll(dataDir).Where(i => i.Index != 0).OrderBy(i => i.Index).ToList();
        var itemRows = items.Select(FormatItemRow).ToList();

        var sb = new StringBuilder();
        sb.Append("-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/ItemSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00002.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- One row per ItemRecord where Index != 0 -- retired/deleted slots (per the runtime\n");
        sb.Append("-- patch ItemReader.ReadAll already applies) are skipped, not seeded as empty rows.\n");
        sb.Append("-- GainSkillNumber translates the legacy \"0 = no skill\" sentinel to NULL (world.Skills\n");
        sb.Append("-- has no SkillId = 0 row -- see 070_skills.sql).\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.Items)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.Items", ItemColumns, itemRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"080_items.sql: {itemRows.Count} item rows -> {outputPath}");
    }

    private static string FormatItemRow(ItemRecord i)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(i.Index),
            SqlSeedWriter.NString(i.Name),
            SqlSeedWriter.NString(i.Description[0]),
            SqlSeedWriter.NString(i.Description[1]),
            SqlSeedWriter.NString(i.Description[2]),
            SqlSeedWriter.Number(i.Type),
            SqlSeedWriter.Number(i.Sort),
            SqlSeedWriter.Number(i.DataNumber2D),
            SqlSeedWriter.Number(i.DataNumber3D),
            SqlSeedWriter.Number(i.AddDataNumber3D),
            SqlSeedWriter.Number(i.Level),
            SqlSeedWriter.Number(i.MartialLevel),
            SqlSeedWriter.Number(i.EquipInfo[0]),
            SqlSeedWriter.Number(i.EquipInfo[1]),
            SqlSeedWriter.Number(i.BuyCost),
            SqlSeedWriter.Number(i.SellCost),
            SqlSeedWriter.Number(i.BuyCost2),
            SqlSeedWriter.Number(i.LevelLimit),
            SqlSeedWriter.Number(i.MartialLevelLimit),
            SqlSeedWriter.Number(i.CheckMonsterDrop),
            SqlSeedWriter.Number(i.CheckNpcSell),
            SqlSeedWriter.Number(i.CheckNpcShop),
            SqlSeedWriter.Number(i.CheckAvatarDrop),
            SqlSeedWriter.Number(i.CheckAvatarTrade),
            SqlSeedWriter.Number(i.CheckAvatarShop),
            SqlSeedWriter.Number(i.CheckImprove),
            SqlSeedWriter.Number(i.CheckHighImprove),
            SqlSeedWriter.Number(i.CheckHighItem),
            SqlSeedWriter.Number(i.CheckLowItem),
            SqlSeedWriter.Number(i.CheckExchange),
            SqlSeedWriter.Number(i.CheckSetItem),
            SqlSeedWriter.Number(i.CheckDateItem),
            SqlSeedWriter.Number(i.Strength),
            SqlSeedWriter.Number(i.Dexterity),
            SqlSeedWriter.Number(i.Vitality),
            SqlSeedWriter.Number(i.Intelligent),
            SqlSeedWriter.Number(i.Luck),
            SqlSeedWriter.Number(i.AttackPower),
            SqlSeedWriter.Number(i.DefensePower),
            SqlSeedWriter.Number(i.AttackSuccess),
            SqlSeedWriter.Number(i.AttackBlock),
            SqlSeedWriter.Number(i.ElementAttackPower),
            SqlSeedWriter.Number(i.ElementDefensePower),
            SqlSeedWriter.Number(i.Critical),
            SqlSeedWriter.Number(i.PotionType[0]),
            SqlSeedWriter.Number(i.PotionType[1]),
            SqlSeedWriter.Number(SqlSeedWriter.ZeroToNull(i.GainSkillNumber)),
            SqlSeedWriter.Number(i.LastAttackBonusInfo[0]),
            SqlSeedWriter.Number(i.LastAttackBonusInfo[1]),
            SqlSeedWriter.Number(i.CapeInfo[0]),
            SqlSeedWriter.Number(i.CapeInfo[1]),
            SqlSeedWriter.Number(i.CapeInfo[2])
        });
    }
}
