using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;
using Fenrir.Tools.LegacyDataImport.Legacy.Records;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

/// <summary>
///     Generates <c>70_seed/world/060_levels.sql</c> from the real <c>005_00001.IMG</c> data
///     (<see cref="LevelReader.ReadAll" />). One row per <see cref="LevelRecord" />, all 145, no filtering --
///     verified the Index set is exactly {1..145} with no gaps/duplicates, so every row is real.
///     <c>RangeInfo[0]</c>/<c>[1]</c> are a contiguous EXP-threshold band per level (verified: every level's
///     RangeInfo[0] equals the previous level's RangeInfo[1] + 1, with zero exceptions across all 145 rows),
///     named ExpRangeMin/ExpRangeMax accordingly. <c>RangeInfo[2]</c> is NOT part of that band (it ranges
///     0-50 while the other two run into the billions) -- it climbs roughly every 5-19 levels up to 50 at
///     level 113, then drops to 0 for the remaining 114-145, an unrelated third value the legacy struct just
///     bundled into the same array. Its exact game-mechanic meaning isn't independently confirmed, so it
///     keeps a neutral, positional column name (RangeInfo3) rather than a guessed one.
/// </summary>
public static class LevelSeedGenerator
{
    private const string LevelColumns =
        "Level, ExpRangeMin, ExpRangeMax, RangeInfo3, AttackPower, DefensePower, AttackSuccess, " +
        "AttackBlock, ElementAttack, Life, Mana";

    public static void Generate(string dataDir, string outputPath)
    {
        var levels = LevelReader.ReadAll(dataDir).OrderBy(l => l.Index).ToList();
        var levelRows = levels.Select(FormatLevelRow).ToList();

        var sb = new StringBuilder();
        sb.Append("-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/LevelSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00001.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- One row per LevelRecord, all 145 -- Index set verified exactly {1..145}, no filtering.\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.Levels)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.Levels", LevelColumns, levelRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"060_levels.sql: {levelRows.Count} level rows -> {outputPath}");
    }

    private static string FormatLevelRow(LevelRecord l)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(l.Index),
            SqlSeedWriter.Number(l.RangeInfo[0]),
            SqlSeedWriter.Number(l.RangeInfo[1]),
            SqlSeedWriter.Number(l.RangeInfo[2]),
            SqlSeedWriter.Number(l.AttackPower),
            SqlSeedWriter.Number(l.DefensePower),
            SqlSeedWriter.Number(l.AttackSuccess),
            SqlSeedWriter.Number(l.AttackBlock),
            SqlSeedWriter.Number(l.ElementAttack),
            SqlSeedWriter.Number(l.Life),
            SqlSeedWriter.Number(l.Mana)
        });
    }
}
