using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;
using Fenrir.Tools.LegacyDataImport.Legacy.Records;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

/// <summary>
///     Generates <c>70_seed/world/060_levels.sql</c> from <see cref="LevelReader.ReadAll" /> (005_00001.IMG),
///     one row per level (all 145, verified no gaps/duplicates). RangeInfo[0..1] is a verified contiguous
///     EXP-threshold band; RangeInfo[2] is an unrelated 0-50 value with unconfirmed meaning, kept as RangeInfo3.
/// </summary>
public static class LevelSeedGenerator
{
    private const string LevelColumns =
        "Level, ExpRangeMin, ExpRangeMax, RangeInfo3, AttackPower, DefensePower, AttackSuccess, " +
        "AttackBlock, ElementAttack, Life, Mana";

    public static void Generate(string dataDir, string outputPath)
    {
        var levels = LevelReader.ReadAll(dataDir).OrderBy(l => l.Index).ToList();
        var levelRows = levels.Select(FormatLevelRow).ToList();

        var sb = new StringBuilder();
        sb.Append("-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/LevelSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00001.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- One row per LevelRecord, all 145 -- Index set verified exactly {1..145}, no filtering.\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.Levels)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.Levels", LevelColumns, levelRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"060_levels.sql: {levelRows.Count} level rows -> {outputPath}");
    }

    private static string FormatLevelRow(LevelRecord l)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(l.Index),
            SqlSeedWriter.Number(l.RangeInfo[0]),
            SqlSeedWriter.Number(l.RangeInfo[1]),
            SqlSeedWriter.Number(l.RangeInfo[2]),
            SqlSeedWriter.Number(l.AttackPower),
            SqlSeedWriter.Number(l.DefensePower),
            SqlSeedWriter.Number(l.AttackSuccess),
            SqlSeedWriter.Number(l.AttackBlock),
            SqlSeedWriter.Number(l.ElementAttack),
            SqlSeedWriter.Number(l.Life),
            SqlSeedWriter.Number(l.Mana)
        });
    }
}
