using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

/// <summary>
///     Generates <c>70_seed/world/071_skill_descriptions.sql</c> from the real <c>005_00003.IMG</c> data
///     (<see cref="SkillReader.ReadAll" />). Normalizes <c>SKILL_INFO</c>'s <c>sDescription[10][51]</c>: one
///     row per non-empty description line, not 10 mostly-empty columns. Real data check before committing to
///     this shape: description-line indices 7-9 are populated in 0 of 153 real (Index != 0) skills, and even
///     indices 0-6 vary from 0 to 7 populated lines per skill (average ~3.9) -- genuinely sparse/variable
///     length, unlike <c>ITEM_INFO</c>'s always-3-line description (kept as plain columns on world.Items).
/// </summary>
public static class SkillDescriptionSeedGenerator
{
    private const string DescriptionColumns = "SkillId, LineIndex, Text";

    public static void Generate(string dataDir, string outputPath)
    {
        var skills = SkillReader.ReadAll(dataDir).Where(s => s.Index != 0).OrderBy(s => s.Index).ToList();
        var descriptionRows = skills
            .SelectMany(s => s.Description.Select((text, line) => (Skill: s, Line: line, Text: text)))
            .Where(x => !string.IsNullOrEmpty(x.Text))
            .Select(x => FormatDescriptionRow(x.Skill.Index, x.Line, x.Text))
            .ToList();

        var sb = new StringBuilder();
        sb.Append(
            "-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/SkillDescriptionSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00003.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- One row per non-empty SkillRecord.Description[10] line, for real (Index != 0) skills.\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.SkillDescriptions)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.SkillDescriptions", DescriptionColumns, descriptionRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"071_skill_descriptions.sql: {descriptionRows.Count} description rows -> {outputPath}");
    }

    private static string FormatDescriptionRow(int skillId, int line, string text)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(skillId),
            SqlSeedWriter.Number(line),
            SqlSeedWriter.NString(text)
        });
    }
}
