using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

/// <summary>
///     Generates <c>70_seed/world/071_skill_descriptions.sql</c> from <see cref="SkillReader.ReadAll" />
///     (005_00003.IMG): one row per non-empty description line (avg ~3.9 of 10 populated per skill), unlike
///     <c>ITEM_INFO</c>'s fixed 3-line description.
/// </summary>
public static class SkillDescriptionSeedGenerator
{
    private const string DescriptionColumns = "SkillId, LineIndex, Text";

    public static void Generate(string dataDir, string outputPath)
    {
        var skills = SkillReader.ReadAll(dataDir).Where(s => s.Index != 0).OrderBy(s => s.Index).ToList();
        var descriptionRows = skills
            .SelectMany(s => s.Description.Select((text, line) => (Skill: s, Line: line, Text: text)))
            .Where(x => !string.IsNullOrEmpty(x.Text))
            .Select(x => FormatDescriptionRow(x.Skill.Index, x.Line, x.Text))
            .ToList();

        var sb = new StringBuilder();
        sb.Append(
            "-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/SkillDescriptionSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00003.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- One row per non-empty SkillRecord.Description[10] line, for real (Index != 0) skills.\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.SkillDescriptions)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.SkillDescriptions", DescriptionColumns, descriptionRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"071_skill_descriptions.sql: {descriptionRows.Count} description rows -> {outputPath}");
    }

    private static string FormatDescriptionRow(int skillId, int line, string text)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(skillId),
            SqlSeedWriter.Number(line),
            SqlSeedWriter.NString(text)
        });
    }
}
