using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;
using Fenrir.Tools.LegacyDataImport.Legacy.Records;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

public static class SkillSeedGenerator
{
    private const string SkillColumns =
        "SkillId, Name, Type, AttackType, DataNumber2D, TribeInfo1, TribeInfo2, LearnSkillPoint, " +
        "MaxUpgradePoint, TotalHitNumber, ValidRadius";

    public static void Generate(string dataDir, string outputPath)
    {
        var skills = SkillReader.ReadAll(dataDir).Where(s => s.Index != 0).OrderBy(s => s.Index).ToList();
        var skillRows = skills.Select(FormatSkillRow).ToList();

        var sb = new StringBuilder();
        sb.Append("-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/SkillSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00003.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- One row per SkillRecord where Index != 0 -- despite no runtime patch existing for\n");
        sb.Append("-- skills, 147 of the 300 raw records are blank placeholder slots that all share\n");
        sb.Append("-- Index == 0, so they are skipped for the same reason items' zeroed slots are.\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.Skills)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.Skills", SkillColumns, skillRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"002_skills.sql: {skillRows.Count} skill rows -> {outputPath}");
    }

    private static string FormatSkillRow(SkillRecord s)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(s.Index),
            SqlSeedWriter.NString(s.Name),
            SqlSeedWriter.Number(s.Type),
            SqlSeedWriter.Number(s.AttackType),
            SqlSeedWriter.Number(s.DataNumber2D),
            SqlSeedWriter.Number(s.TribeInfo[0]),
            SqlSeedWriter.Number(s.TribeInfo[1]),
            SqlSeedWriter.Number(s.LearnSkillPoint),
            SqlSeedWriter.Number(s.MaxUpgradePoint),
            SqlSeedWriter.Number(s.TotalHitNumber),
            SqlSeedWriter.Number(s.ValidRadius)
        });
    }
}
