using System.Text;
using Fenrir.Tools.LegacyDataImport.Legacy.Readers;
using Fenrir.Tools.LegacyDataImport.Legacy.Records;

namespace Fenrir.Tools.LegacyDataImport.Legacy.Seeding;

public static class SkillGradeSeedGenerator
{
    private const string GradeColumns =
        "SkillId, GradeIndex, ManaUse, RecoverInfo1, RecoverInfo2, StunAttack, StunDefense, FastRunSpeed, " +
        "AttackInfo1, AttackInfo2, AttackInfo3, RunTime, ChargingDamageUp, AttackPowerUp, DefensePowerUp, " +
        "AttackSuccessUp, AttackBlockUp, ElementAttackUp, ElementDefenseUp, AttackSpeedUp, RunSpeedUp, " +
        "ShieldLifeUp, LuckUp, CriticalUp, ReturnSuccessUp, StunDefenseUp, DestroySuccessUp";

    public static void Generate(string dataDir, string outputPath)
    {
        var skills = SkillReader.ReadAll(dataDir).Where(s => s.Index != 0).OrderBy(s => s.Index).ToList();
        var gradeRows = skills
            .SelectMany(s => s.GradeInfo.Select((grade, idx) => (Skill: s, GradeIndex: idx, Grade: grade)))
            .Select(x => FormatGradeRow(x.Skill.Index, x.GradeIndex, x.Grade))
            .ToList();

        var sb = new StringBuilder();
        sb.Append("-- Generated by Tools/Fenrir.Tools.LegacyDataImport/Legacy/Seeding/SkillGradeSeedGenerator.cs\n");
        sb.Append("-- from Server/BuildEU33/DATA (005_00003.IMG). Regenerate rather than hand-edit.\n");
        sb.Append("-- Exactly 2 rows (grade 0/1) per real (Index != 0) SkillRecord -- never sparse.\n");
        sb.Append("IF NOT EXISTS (SELECT 1 FROM world.SkillGrades)\n");
        sb.Append("BEGIN\n");

        SqlSeedWriter.WriteInserts(sb, "world.SkillGrades", GradeColumns, gradeRows);

        sb.Append("END;\n");

        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"072_skill_grades.sql: {gradeRows.Count} grade rows -> {outputPath}");
    }

    private static string FormatGradeRow(int skillId, int gradeIndex, SkillGradeRecord g)
    {
        return string.Join(", ", new[]
        {
            SqlSeedWriter.Number(skillId),
            SqlSeedWriter.Number(gradeIndex),
            SqlSeedWriter.Number(g.ManaUse),
            SqlSeedWriter.Number(g.RecoverInfo[0]),
            SqlSeedWriter.Number(g.RecoverInfo[1]),
            SqlSeedWriter.Number(g.StunAttack),
            SqlSeedWriter.Number(g.StunDefense),
            SqlSeedWriter.Number(g.FastRunSpeed),
            SqlSeedWriter.Number(g.AttackInfo[0]),
            SqlSeedWriter.Number(g.AttackInfo[1]),
            SqlSeedWriter.Number(g.AttackInfo[2]),
            SqlSeedWriter.Number(g.RunTime),
            SqlSeedWriter.Number(g.ChargingDamageUp),
            SqlSeedWriter.Number(g.AttackPowerUp),
            SqlSeedWriter.Number(g.DefensePowerUp),
            SqlSeedWriter.Number(g.AttackSuccessUp),
            SqlSeedWriter.Number(g.AttackBlockUp),
            SqlSeedWriter.Number(g.ElementAttackUp),
            SqlSeedWriter.Number(g.ElementDefenseUp),
            SqlSeedWriter.Number(g.AttackSpeedUp),
            SqlSeedWriter.Number(g.RunSpeedUp),
            SqlSeedWriter.Number(g.ShieldLifeUp),
            SqlSeedWriter.Number(g.LuckUp),
            SqlSeedWriter.Number(g.CriticalUp),
            SqlSeedWriter.Number(g.ReturnSuccessUp),
            SqlSeedWriter.Number(g.StunDefenseUp),
            SqlSeedWriter.Number(g.DestroySuccessUp)
        });
    }
}
