CREATE TABLE game.ProxyShopNames
(
    CharacterId INT          NOT NULL,
    ShopName    NVARCHAR(48) NOT NULL
        CONSTRAINT DF_ProxyShopNames_ShopName DEFAULT N'',
    CONSTRAINT PK_ProxyShopNames PRIMARY KEY NONCLUSTERED HASH (CharacterId) WITH (BUCKET_COUNT = 131072)
)
    WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);
