<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Fenrir.LoginServer-99c83373-0ef8-4396-a255-5470a8db0f55</UserSecretsId>
    <FenrirExecutable>true</FenrirExecutable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Fenrir.Contracts\Fenrir.Contracts.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Abstractions\Fenrir.Network.Abstractions.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Serialization\Fenrir.Network.Serialization.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Transport\Fenrir.Network.Transport.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Framing\Fenrir.Network.Framing.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Dispatch\Fenrir.Network.Dispatch.csproj"/>
    <ProjectReference Include="..\..\Infrastructure\Fenrir.Data\Fenrir.Data.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Login\Fenrir.Application.Login.csproj"/>
    <ProjectReference Include="..\..\Orchestration\Fenrir.ServiceDefaults\Fenrir.ServiceDefaults.csproj"/>
  </ItemGroup>


</Project>
