<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Stats\Fenrir.Application.Game.Stats.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.GameData\Fenrir.Application.Game.GameData.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Domain\Fenrir.Application.Game.Domain.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Abstractions\Fenrir.Application.Game.Abstractions.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Services\Fenrir.Application.Game.Services.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Handlers\Fenrir.Application.Game.Handlers.csproj"/>
    <ProjectReference Include="..\..\Application\Fenrir.Application.Game.Hosting\Fenrir.Application.Game.Hosting.csproj"/>
    <ProjectReference Include="..\..\Network\Fenrir.Network.Abstractions\Fenrir.Network.Abstractions.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="obj_tribebanktax\Fenrir.Application.Game.Tests.csproj.nuget.dgspec.json"/>
    <None Remove="obj_tribebanktax\Fenrir.Application.Game.Tests.csproj.nuget.g.targets"/>
  </ItemGroup>

</Project>
