using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

/// <summary>
///     Emits <c>Fenrir.Contracts.Wire.{Login|Zone}MessageFactory</c> (spec §5.6): wraps outgoing
///     <c>Compressed = true</c> packets (only 2 in the whole M1 protocol) in ZPACKET + LZ4. Only emitted if the
///     server has at least one compressed packet — no empty class for Login (no compressed packet there yet).
/// </summary>
internal static class MessageFactoryEmitter
{
    public static string HintNameFor(FenrirServer server)
    {
        return server == FenrirServer.Login ? "LoginMessageFactory.g.cs" : "ZoneMessageFactory.g.cs";
    }

    public static string? Emit(FenrirServer server, ImmutableArray<TypeModel> packets)
    {
        var compressed = packets
            .Where(p => p.Server == server && p is { Direction: FenrirDirection.Outgoing, Compressed: true })
            .OrderBy(p => p.Opcode)
            .ToImmutableArray();

        if (compressed.Length == 0)
            return null;

        var className = server == FenrirServer.Login ? "LoginMessageFactory" : "ZoneMessageFactory";

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("namespace Fenrir.Contracts.Wire;");
        writer.Line();
        writer.Line("/// <summary>");
        writer.Line(
            "/// ZC_ZPACKET_OK_SEND envelope (§3.5): tProtocol(1) + isCompress(4) + originalSize(4) + compressSize(4) + payload.");
        writer.Line(
            "/// Falls back to uncompressed (isCompress=0, payload=originalSize bytes) if LZ4Codec.Encode returns ≤0.");
        writer.Line("/// No symmetric decompression here: these packets are S→C only, never received by the server.");
        writer.Line("/// </summary>");
        writer.Line($"public static class {className}");
        writer.OpenBrace();

        for (var i = 0; i < compressed.Length; i++)
        {
            if (i > 0)
                writer.Line();

            EmitEncodeMethod(writer, compressed[i]);
        }

        writer.CloseBrace();
        return writer.ToString();
    }

    private static void EmitEncodeMethod(IndentedWriter writer, TypeModel packet)
    {
        writer.Line($"public static byte[] Encode(in {packet.FullTypeName} packet)");
        writer.OpenBrace();
        writer.Line($"var payloadSize = {packet.FullTypeName}.PayloadSize;");
        writer.Line("var plainRented = global::System.Buffers.ArrayPool<byte>.Shared.Rent(payloadSize);");
        writer.Line("try");
        writer.OpenBrace();
        writer.Line("var plainSpan = plainRented.AsSpan(0, payloadSize);");
        writer.Line("packet.Write(plainSpan);");
        writer.Line();
        writer.Line("var maxCompressedSize = global::K4os.Compression.LZ4.LZ4Codec.MaximumOutputSize(payloadSize);");
        writer.Line("var compressedRented = global::System.Buffers.ArrayPool<byte>.Shared.Rent(maxCompressedSize);");
        writer.Line("try");
        writer.OpenBrace();
        writer.Line("var compressedSpan = compressedRented.AsSpan(0, maxCompressedSize);");
        writer.Line(
            "var compressSize = global::K4os.Compression.LZ4.LZ4Codec.Encode(plainSpan, compressedSpan, global::K4os.Compression.LZ4.LZ4Level.L00_FAST);");
        writer.Line("var isCompress = compressSize > 0;");
        writer.Line("var bodySize = isCompress ? compressSize : payloadSize;");
        writer.Line("var frame = new byte[13 + bodySize];");
        writer.Line($"frame[0] = {packet.FullTypeName}.Opcode;");
        writer.Line(
            "global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(frame.AsSpan(1, 4), isCompress ? 1 : 0);");
        writer.Line(
            "global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(frame.AsSpan(5, 4), payloadSize);");
        writer.Line(
            "global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(frame.AsSpan(9, 4), isCompress ? compressSize : 0);");
        writer.Line("(isCompress ? compressedSpan.Slice(0, compressSize) : plainSpan).CopyTo(frame.AsSpan(13));");
        writer.Line("return frame;");
        writer.CloseBrace();
        writer.Line("finally");
        writer.OpenBrace();
        writer.Line("global::System.Buffers.ArrayPool<byte>.Shared.Return(compressedRented);");
        writer.CloseBrace();
        writer.CloseBrace();
        writer.Line("finally");
        writer.OpenBrace();
        writer.Line("global::System.Buffers.ArrayPool<byte>.Shared.Return(plainRented);");
        writer.CloseBrace();
        writer.CloseBrace();
    }
}
