using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

/// <summary>Emits <c>Fenrir.Contracts.Wire.OpcodeRegistry</c> from all discovered <c>[FenrirPacket]</c>.</summary>
internal static class OpcodeRegistryEmitter
{
    public const string HintName = "OpcodeRegistry.g.cs";

    public static string Emit(ImmutableArray<TypeModel> packets)
    {
        var ordered = packets
            .OrderBy(p => p.Server)
            .ThenBy(p => p.Direction)
            .ThenBy(p => p.Opcode)
            .ToImmutableArray();

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("namespace Fenrir.Contracts.Wire;");
        writer.Line();
        writer.Line(
            "/// <summary>(Server, Direction, Opcode) → (frame size, type name) table generated from discovered [FenrirPacket].</summary>");
        writer.Line("public static class OpcodeRegistry");
        writer.OpenBrace();

        writer.Line(
            "public static int FrameSizeOf(FenrirServer server, FenrirDirection direction, byte opcode) => (server, direction, opcode) switch");
        writer.OpenBrace();
        foreach (var packet in ordered)
        {
            var headerSize = packet.Direction == FenrirDirection.Incoming
                ? WireHeaderSizes.ClientPacketSize
                : WireHeaderSizes.DefaultPacketSize;
            var frameSize = packet.FieldsSize + headerSize;
            writer.Line(
                $"({ServerLiteral(packet.Server)}, {DirectionLiteral(packet.Direction)}, {packet.Opcode}) => {frameSize},");
        }

        writer.Line(
            "_ => throw new global::System.ArgumentOutOfRangeException(nameof(opcode), opcode, $\"Unknown legacy opcode for ({server}, {direction}).\"),");
        writer.CloseBraceSemicolon();

        writer.Line();
        writer.Line(
            "public static string NameOf(FenrirServer server, FenrirDirection direction, byte opcode) => (server, direction, opcode) switch");
        writer.OpenBrace();
        foreach (var packet in ordered)
            writer.Line(
                $"({ServerLiteral(packet.Server)}, {DirectionLiteral(packet.Direction)}, {packet.Opcode}) => \"{packet.FullTypeName}\",");
        writer.Line(
            "_ => throw new global::System.ArgumentOutOfRangeException(nameof(opcode), opcode, $\"Unknown legacy opcode for ({server}, {direction}).\"),");
        writer.CloseBraceSemicolon();

        writer.CloseBrace();
        return writer.ToString();
    }

    private static string ServerLiteral(FenrirServer server)
    {
        return server == FenrirServer.Login ? "FenrirServer.Login" : "FenrirServer.Zone";
    }

    private static string DirectionLiteral(FenrirDirection direction)
    {
        return direction == FenrirDirection.Incoming ? "FenrirDirection.Incoming" : "FenrirDirection.Outgoing";
    }
}
