using System;
using System.Globalization;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

/// <summary>Emits the missing <c>partial</c> part of a <c>[FenrirPacket]</c>/<c>[FenrirWireType]</c>.</summary>
internal static class PacketEmitter
{
    public static string Emit(TypeModel model)
    {
        var writer = new IndentedWriter();
        var sizeMember = model.IsPacket ? "PayloadSize" : "WireSize";

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {model.Namespace};");
        writer.Line();
        writer.Line($"partial record struct {model.TypeName}");
        writer.OpenBrace();

        if (model.IsPacket)
        {
            writer.Line($"public static byte Opcode => {FormatByteLiteral(model.Opcode)};");
            writer.Line();
        }

        writer.Line($"public static int {sizeMember} => {model.FieldsSize};");

        var emitTryRead = !model.IsPacket || model.ImplementsIncoming;
        var emitWrite = !model.IsPacket || model.ImplementsOutgoing;

        if (model.IsPacket && model.ImplementsOutgoing)
        {
            writer.Line();
            writer.Line(
                $"public static global::Fenrir.Network.Abstractions.WireObfuscationMode Obfuscation => global::Fenrir.Network.Abstractions.WireObfuscationMode.{model.Obfuscation};");
        }

        if (emitTryRead)
        {
            writer.Line();
            EmitTryRead(writer, model, sizeMember);
        }

        if (emitWrite)
        {
            writer.Line();
            EmitWrite(writer, model, sizeMember);
        }

        writer.CloseBrace();

        return writer.ToString();
    }

    private static void EmitTryRead(IndentedWriter writer, TypeModel model, string sizeMember)
    {
        writer.Line(
            $"public static bool TryRead(global::System.ReadOnlySpan<byte> source, out {model.TypeName} packet)");
        writer.OpenBrace();
        writer.Line($"if (source.Length < {sizeMember})");
        writer.OpenBrace();
        writer.Line("packet = default;");
        writer.Line("return false;");
        writer.CloseBrace();

        if (model.Fields.Length > 0)
            writer.Line();

        foreach (var field in model.Fields)
        {
            var localName = "v_" + field.PropertyName;
            var slice = $"source.Slice({field.Offset}, {field.OwnSize})";

            // Switch EXPRESSION (not statement): an unhandled FieldShape trips CS8509, a solution-wide
            // build ERROR via TreatWarningsAsErrors, instead of silently emitting zero bytes for that field.
            Action emitField = field.Shape switch
            {
                FieldShape.Int32 => () => writer.Line(
                    $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian({slice});"),
                FieldShape.UInt32 => () => writer.Line(
                    $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian({slice});"),
                FieldShape.Byte => () => writer.Line($"var {localName} = source[{field.Offset}];"),
                FieldShape.Single => () => writer.Line(
                    $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadSingleLittleEndian({slice});"),
                FieldShape.Int64 => () => writer.Line(
                    $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian({slice});"),
                FieldShape.FixedString => () => writer.Line(
                    $"var {localName} = global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.ReadFixedString({slice});"),
                FieldShape.Int32Array => () => writer.Line(
                    $"var {localName} = global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.ReadInt32Array({slice});"),
                FieldShape.SingleArray => () => writer.Line(
                    $"var {localName} = global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.ReadSingleArray({slice});"),
                FieldShape.ByteArray => () => writer.Line(
                    $"var {localName} = global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.ReadByteArray({slice});"),
                FieldShape.FixedStringArray => () => writer.Line(
                    $"var {localName} = global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.ReadFixedStringRows({slice}, {field.StringLength});"),
                FieldShape.Nested => () =>
                {
                    writer.Line($"if (!{field.NestedTypeFullName}.TryRead({slice}, out var {localName}))");
                    writer.OpenBrace();
                    writer.Line("packet = default;");
                    writer.Line("return false;");
                    writer.CloseBrace();
                },
                FieldShape.NestedArray => () =>
                {
                    writer.Line($"var {localName} = new {field.NestedTypeFullName}[{field.ElementCount}];");
                    writer.Line($"for (var i = 0; i < {field.ElementCount}; i++)");
                    writer.OpenBrace();
                    writer.Line(
                        $"if (!{field.NestedTypeFullName}.TryRead(source.Slice({field.Offset} + i * {field.NestedSize}, {field.NestedSize}), out {localName}[i]))");
                    writer.OpenBrace();
                    writer.Line("packet = default;");
                    writer.Line("return false;");
                    writer.CloseBrace();
                    writer.CloseBrace();
                },
                // Roslyn never treats a switch expression over an enum as exhaustive from named members
                // alone (the underlying integral type can hold unnamed values), so a discard-free version
                // of this switch fails to build unconditionally rather than only on a genuinely missed
                // case. This throwing discard is therefore load-bearing, not decorative: every FieldShape
                // above is named explicitly, so this arm is only reachable if FieldShape gains a new
                // member that isn't added here too - turning that into a loud generator-time failure
                // instead of the silent zero-byte emission this switch used to produce.
                _ => () => throw new NotSupportedException(
                    $"PacketEmitter.EmitTryRead has no case for FieldShape.{field.Shape} (field '{field.PropertyName}').")
            };

            emitField();
        }

        writer.Line();

        if (model.Fields.Length == 0)
        {
            writer.Line($"packet = new {model.TypeName}();");
        }
        else
        {
            writer.Line($"packet = new {model.TypeName}");
            writer.OpenBrace();
            foreach (var field in model.Fields)
                writer.Line($"{field.PropertyName} = v_{field.PropertyName},");
            writer.CloseBraceSemicolon();
        }

        writer.Line("return true;");
        writer.CloseBrace();
    }

    private static void EmitWrite(IndentedWriter writer, TypeModel model, string sizeMember)
    {
        writer.Line("public int Write(global::System.Span<byte> destination)");
        writer.OpenBrace();

        FieldModel? legacyUidField = null;

        foreach (var field in model.Fields)
        {
            if (field.ReservedBefore > 0)
                writer.Line(
                    $"destination.Slice({field.Offset - field.ReservedBefore}, {field.ReservedBefore}).Clear();");

            var slice = $"destination.Slice({field.Offset}, {field.OwnSize})";
            var access = field.PropertyName;

            // Switch EXPRESSION (not statement): an unhandled FieldShape trips CS8509, a solution-wide
            // build ERROR via TreatWarningsAsErrors, instead of silently emitting zero bytes for that field.
            Action emitField = field.Shape switch
            {
                FieldShape.Int32 => () => writer.Line(
                    $"global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian({slice}, {access});"),
                FieldShape.UInt32 => () => writer.Line(
                    $"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian({slice}, {access});"),
                FieldShape.Byte => () => writer.Line($"destination[{field.Offset}] = {access};"),
                FieldShape.Single => () => writer.Line(
                    $"global::System.Buffers.Binary.BinaryPrimitives.WriteSingleLittleEndian({slice}, {access});"),
                FieldShape.Int64 => () => writer.Line(
                    $"global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian({slice}, {access});"),
                FieldShape.FixedString => () => writer.Line(
                    $"global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.WriteFixedString({slice}, {access});"),
                FieldShape.Int32Array => () => writer.Line(
                    $"global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.WriteInt32Array({slice}, {access});"),
                FieldShape.SingleArray => () => writer.Line(
                    $"global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.WriteSingleArray({slice}, {access});"),
                FieldShape.ByteArray => () => writer.Line(
                    $"global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.WriteByteArray({slice}, {access});"),
                FieldShape.FixedStringArray => () => writer.Line(
                    $"global::Fenrir.Network.Serialization.Wire.LegacyWireCodec.WriteFixedStringRows({slice}, {access}, {field.StringLength});"),
                FieldShape.Nested => () => writer.Line($"{access}.Write({slice});"),
                FieldShape.NestedArray => () =>
                {
                    writer.Line($"for (var i = 0; i < {field.ElementCount}; i++)");
                    writer.OpenBrace();
                    writer.Line(
                        $"{access}[i].Write(destination.Slice({field.Offset} + i * {field.NestedSize}, {field.NestedSize}));");
                    writer.CloseBrace();
                },
                // See the matching discard arm in EmitTryRead: Roslyn can't prove enum-switch exhaustiveness
                // from named members alone, so this throwing discard is what stands in for a compile-time
                // CS8509 here - every named FieldShape is handled above, so this only fires if the enum
                // gains a member this switch wasn't updated for.
                _ => () => throw new NotSupportedException(
                    $"PacketEmitter.EmitWrite has no case for FieldShape.{field.Shape} (field '{field.PropertyName}').")
            };

            emitField();

            if (field.AvatarXor != AvatarXorKind.None)
                switch (field.AvatarXor)
                {
                    case AvatarXorKind.Int:
                        writer.Line($"global::Fenrir.Network.Compression.WireXor.XorInt({slice});");
                        break;
                    case AvatarXorKind.IntArray:
                        writer.Line($"global::Fenrir.Network.Compression.WireXor.XorIntArray({slice});");
                        break;
                    case AvatarXorKind.Char:
                        writer.Line($"global::Fenrir.Network.Compression.WireXor.XorChar({slice});");
                        break;
                    case AvatarXorKind.Char2:
                        writer.Line(
                            $"global::Fenrir.Network.Compression.WireXor.XorChar2Rows({slice}, {field.AvatarXorRowLength});");
                        break;
                }

            if (field.IsLegacyUidField)
                legacyUidField = field;
        }

        if (legacyUidField is not null)
        {
            writer.Line();
            writer.Line(
                "// [ObfuscatedUidField] (§3.3): double-XOR of tID, independent of the global XOR_PACKET applied later by the send layer.");
            writer.Line(
                $"global::Fenrir.Network.Compression.WireXor.ApplyUidXor(destination.Slice({legacyUidField.Offset}, {legacyUidField.OwnSize}));");
        }

        writer.Line();
        writer.Line($"return {sizeMember};");
        writer.CloseBrace();
    }

    private static string FormatByteLiteral(byte value)
    {
        return value.ToString(CultureInfo.InvariantCulture);
    }
}
