using System.Globalization;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

/// <summary>
///     Emits the missing <c>partial</c> part of a <c>[FenrirPacket]</c>/<c>[FenrirWireType]</c>:
///     <c>Opcode</c>/<c>PayloadSize</c>|<c>WireSize</c>/<c>TryRead</c>/<c>Write</c>, plus <c>ApplyGlobalXor</c>
///     for packets with global obfuscation (spec §5.1).
/// </summary>
internal static class PacketEmitter
{
    public static string Emit(TypeModel model)
    {
        var writer = new IndentedWriter();
        var sizeMember = model.IsPacket ? "PayloadSize" : "WireSize";

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {model.Namespace};");
        writer.Line();
        writer.Line($"partial record struct {model.TypeName}");
        writer.OpenBrace();

        if (model.IsPacket)
        {
            writer.Line($"public static byte Opcode => {FormatByteLiteral(model.Opcode)};");
            writer.Line();
        }

        writer.Line($"public static int {sizeMember} => {model.FieldsSize};");

        var emitTryRead = !model.IsPacket || model.ImplementsIncoming;
        var emitWrite = !model.IsPacket || model.ImplementsOutgoing;

        if (model.IsPacket && model.ImplementsOutgoing)
        {
            writer.Line();
            writer.Line(
                $"public static global::Fenrir.Contracts.Wire.WireObfuscationMode Obfuscation => global::Fenrir.Contracts.Wire.WireObfuscationMode.{model.Obfuscation};");
        }

        if (emitTryRead)
        {
            writer.Line();
            EmitTryRead(writer, model, sizeMember);
        }

        if (emitWrite)
        {
            writer.Line();
            EmitWrite(writer, model, sizeMember);
        }

        writer.CloseBrace();

        return writer.ToString();
    }

    private static void EmitTryRead(IndentedWriter writer, TypeModel model, string sizeMember)
    {
        writer.Line(
            $"public static bool TryRead(global::System.ReadOnlySpan<byte> source, out {model.TypeName} packet)");
        writer.OpenBrace();
        writer.Line($"if (source.Length < {sizeMember})");
        writer.OpenBrace();
        writer.Line("packet = default;");
        writer.Line("return false;");
        writer.CloseBrace();

        if (model.Fields.Length > 0)
            writer.Line();

        foreach (var field in model.Fields)
        {
            var localName = "v_" + field.PropertyName;
            var slice = $"source.Slice({field.Offset}, {field.OwnSize})";

            switch (field.Shape)
            {
                case FieldShape.Int32:
                    writer.Line(
                        $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian({slice});");
                    break;
                case FieldShape.UInt32:
                    writer.Line(
                        $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian({slice});");
                    break;
                case FieldShape.Byte:
                    writer.Line($"var {localName} = source[{field.Offset}];");
                    break;
                case FieldShape.Single:
                    writer.Line(
                        $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadSingleLittleEndian({slice});");
                    break;
                case FieldShape.Int64:
                    writer.Line(
                        $"var {localName} = global::System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian({slice});");
                    break;
                case FieldShape.FixedString:
                    writer.Line(
                        $"var {localName} = global::Fenrir.Contracts.Wire.LegacyWireCodec.ReadFixedString({slice});");
                    break;
                case FieldShape.Int32Array:
                    writer.Line(
                        $"var {localName} = global::Fenrir.Contracts.Wire.LegacyWireCodec.ReadInt32Array({slice});");
                    break;
                case FieldShape.SingleArray:
                    writer.Line(
                        $"var {localName} = global::Fenrir.Contracts.Wire.LegacyWireCodec.ReadSingleArray({slice});");
                    break;
                case FieldShape.ByteArray:
                    writer.Line(
                        $"var {localName} = global::Fenrir.Contracts.Wire.LegacyWireCodec.ReadByteArray({slice});");
                    break;
                case FieldShape.FixedStringArray:
                    writer.Line(
                        $"var {localName} = global::Fenrir.Contracts.Wire.LegacyWireCodec.ReadFixedStringRows({slice}, {field.StringLength});");
                    break;
                case FieldShape.Nested:
                    writer.Line($"if (!{field.NestedTypeFullName}.TryRead({slice}, out var {localName}))");
                    writer.OpenBrace();
                    writer.Line("packet = default;");
                    writer.Line("return false;");
                    writer.CloseBrace();
                    break;
                case FieldShape.NestedArray:
                    writer.Line($"var {localName} = new {field.NestedTypeFullName}[{field.ElementCount}];");
                    writer.Line($"for (var i = 0; i < {field.ElementCount}; i++)");
                    writer.OpenBrace();
                    writer.Line(
                        $"if (!{field.NestedTypeFullName}.TryRead(source.Slice({field.Offset} + i * {field.NestedSize}, {field.NestedSize}), out {localName}[i]))");
                    writer.OpenBrace();
                    writer.Line("packet = default;");
                    writer.Line("return false;");
                    writer.CloseBrace();
                    writer.CloseBrace();
                    break;
            }
        }

        writer.Line();

        if (model.Fields.Length == 0)
        {
            writer.Line($"packet = new {model.TypeName}();");
        }
        else
        {
            writer.Line($"packet = new {model.TypeName}");
            writer.OpenBrace();
            foreach (var field in model.Fields)
                writer.Line($"{field.PropertyName} = v_{field.PropertyName},");
            writer.CloseBraceSemicolon();
        }

        writer.Line("return true;");
        writer.CloseBrace();
    }

    private static void EmitWrite(IndentedWriter writer, TypeModel model, string sizeMember)
    {
        writer.Line("public int Write(global::System.Span<byte> destination)");
        writer.OpenBrace();

        FieldModel? legacyUidField = null;

        foreach (var field in model.Fields)
        {
            if (field.ReservedBefore > 0)
                writer.Line(
                    $"destination.Slice({field.Offset - field.ReservedBefore}, {field.ReservedBefore}).Clear();");

            var slice = $"destination.Slice({field.Offset}, {field.OwnSize})";
            var access = field.PropertyName;

            switch (field.Shape)
            {
                case FieldShape.Int32:
                    writer.Line(
                        $"global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian({slice}, {access});");
                    break;
                case FieldShape.UInt32:
                    writer.Line(
                        $"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian({slice}, {access});");
                    break;
                case FieldShape.Byte:
                    writer.Line($"destination[{field.Offset}] = {access};");
                    break;
                case FieldShape.Single:
                    writer.Line(
                        $"global::System.Buffers.Binary.BinaryPrimitives.WriteSingleLittleEndian({slice}, {access});");
                    break;
                case FieldShape.Int64:
                    writer.Line(
                        $"global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian({slice}, {access});");
                    break;
                case FieldShape.FixedString:
                    writer.Line($"global::Fenrir.Contracts.Wire.LegacyWireCodec.WriteFixedString({slice}, {access});");
                    break;
                case FieldShape.Int32Array:
                    writer.Line($"global::Fenrir.Contracts.Wire.LegacyWireCodec.WriteInt32Array({slice}, {access});");
                    break;
                case FieldShape.SingleArray:
                    writer.Line($"global::Fenrir.Contracts.Wire.LegacyWireCodec.WriteSingleArray({slice}, {access});");
                    break;
                case FieldShape.ByteArray:
                    writer.Line($"global::Fenrir.Contracts.Wire.LegacyWireCodec.WriteByteArray({slice}, {access});");
                    break;
                case FieldShape.FixedStringArray:
                    writer.Line(
                        $"global::Fenrir.Contracts.Wire.LegacyWireCodec.WriteFixedStringRows({slice}, {access}, {field.StringLength});");
                    break;
                case FieldShape.Nested:
                    writer.Line($"{access}.Write({slice});");
                    break;
                case FieldShape.NestedArray:
                    writer.Line($"for (var i = 0; i < {field.ElementCount}; i++)");
                    writer.OpenBrace();
                    writer.Line(
                        $"{access}[i].Write(destination.Slice({field.Offset} + i * {field.NestedSize}, {field.NestedSize}));");
                    writer.CloseBrace();
                    break;
            }

            if (field.AvatarXor != AvatarXorKind.None)
                switch (field.AvatarXor)
                {
                    case AvatarXorKind.Int:
                        writer.Line($"global::Fenrir.Contracts.Wire.WireXor.XorInt({slice});");
                        break;
                    case AvatarXorKind.IntArray:
                        writer.Line($"global::Fenrir.Contracts.Wire.WireXor.XorIntArray({slice});");
                        break;
                    case AvatarXorKind.Char:
                        writer.Line($"global::Fenrir.Contracts.Wire.WireXor.XorChar({slice});");
                        break;
                    case AvatarXorKind.Char2:
                        writer.Line(
                            $"global::Fenrir.Contracts.Wire.WireXor.XorChar2Rows({slice}, {field.AvatarXorRowLength});");
                        break;
                }

            if (field.IsLegacyUidField)
                legacyUidField = field;
        }

        if (legacyUidField is not null)
        {
            writer.Line();
            writer.Line(
                "// [ObfuscatedUidField] (§3.3): double-XOR of tID, independent of the global XOR_PACKET applied later by the send layer.");
            writer.Line(
                $"global::Fenrir.Contracts.Wire.WireXor.ApplyUidXor(destination.Slice({legacyUidField.Offset}, {legacyUidField.OwnSize}));");
        }

        writer.Line();
        writer.Line($"return {sizeMember};");
        writer.CloseBrace();
    }

    private static string FormatByteLiteral(byte value)
    {
        return value.ToString(CultureInfo.InvariantCulture);
    }
}
