namespace Fenrir.Generators.Protocol.Emitters;

/// <summary>
///     Emits <c>LegacyWireCodec</c> once instead of regenerating these conversions inline per field (e.g.
///     AVATAR_INFO's ~190 fields).
/// </summary>
internal static class RuntimeHelpersEmitter
{
    public const string HintName = "LegacyWireCodec.g.cs";

    public const string Source = """
                                 // <auto-generated/>
                                 #nullable enable

                                 namespace Fenrir.Contracts.Wire;

                                 /// <summary>
                                 /// (De)serialization primitives shared by code emitted by Fenrir.Generators.Protocol.
                                 /// Strings use <see cref="global::System.Text.Encoding.Latin1"/> (wire contract §7.6);
                                 /// scalars are little-endian (via <see cref="global::System.Buffers.Binary.BinaryPrimitives"/>).
                                 /// </summary>
                                 internal static class LegacyWireCodec
                                 {
                                     public static string ReadFixedString(global::System.ReadOnlySpan<byte> source)
                                     {
                                         var nul = source.IndexOf((byte)0);
                                         return global::System.Text.Encoding.Latin1.GetString(nul < 0 ? source : source.Slice(0, nul));
                                     }

                                     public static void WriteFixedString(global::System.Span<byte> destination, string value)
                                     {
                                         destination.Clear();
                                         var count = global::System.Math.Min(value.Length, destination.Length);
                                         if (count > 0)
                                             global::System.Text.Encoding.Latin1.GetBytes(value.AsSpan(0, count), destination);
                                     }

                                     public static string[] ReadFixedStringRows(global::System.ReadOnlySpan<byte> source, int rowLength)
                                     {
                                         var result = new string[source.Length / rowLength];
                                         for (var i = 0; i < result.Length; i++)
                                             result[i] = ReadFixedString(source.Slice(i * rowLength, rowLength));
                                         return result;
                                     }

                                     public static void WriteFixedStringRows(global::System.Span<byte> destination, string[] values, int rowLength)
                                     {
                                         for (var i = 0; i < values.Length; i++)
                                             WriteFixedString(destination.Slice(i * rowLength, rowLength), values[i]);
                                     }

                                     public static int[] ReadInt32Array(global::System.ReadOnlySpan<byte> source)
                                     {
                                         var result = new int[source.Length / 4];
                                         for (var i = 0; i < result.Length; i++)
                                             result[i] = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(i * 4, 4));
                                         return result;
                                     }

                                     public static void WriteInt32Array(global::System.Span<byte> destination, int[] values)
                                     {
                                         for (var i = 0; i < values.Length; i++)
                                             global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(i * 4, 4), values[i]);
                                     }

                                     public static float[] ReadSingleArray(global::System.ReadOnlySpan<byte> source)
                                     {
                                         var result = new float[source.Length / 4];
                                         for (var i = 0; i < result.Length; i++)
                                             result[i] = global::System.Buffers.Binary.BinaryPrimitives.ReadSingleLittleEndian(source.Slice(i * 4, 4));
                                         return result;
                                     }

                                     public static void WriteSingleArray(global::System.Span<byte> destination, float[] values)
                                     {
                                         for (var i = 0; i < values.Length; i++)
                                             global::System.Buffers.Binary.BinaryPrimitives.WriteSingleLittleEndian(destination.Slice(i * 4, 4), values[i]);
                                     }

                                     public static byte[] ReadByteArray(global::System.ReadOnlySpan<byte> source) => source.ToArray();

                                     public static void WriteByteArray(global::System.Span<byte> destination, byte[] values) => values.AsSpan().CopyTo(destination);
                                 }

                                 """;
}
