using System.Collections.Immutable;
using System.Linq;
using Fenrir.Generators.Analysis.Model;
using Fenrir.Generators.Analysis.Support;

namespace Fenrir.Generators.Protocol.Emitters;

internal static class SessionStateGateEmitter
{
    public const string HintName = "SessionStateGate.g.cs";

    public static string Emit(ImmutableArray<TypeModel> packets)
    {
        var server = packets[0].Server;
        var (className, stateEnum) = server == FenrirServer.Login
            ? ("LoginSessionStateGate", WellKnownNames.LoginSessionStateEnum)
            : ("ZoneSessionStateGate", WellKnownNames.ZoneSessionStateEnum);

        var entries = packets
            .Where(p => p is { Direction: FenrirDirection.Incoming, AllowedStates.Length: > 0 })
            .OrderBy(p => p.Opcode)
            .ToImmutableArray();

        var writer = new IndentedWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("namespace Fenrir.Network.Serialization.Wire;");
        writer.Line();
        writer.Line("/// <summary>");
        writer.Line(
            "/// An opcode with no declared [FenrirPacket(AllowedStates = [...])] is legal in any session state");
        writer.Line("/// (e.g. handshake op 0): <c>Allows</c> then always returns <c>true</c> for that opcode.");
        writer.Line("/// </summary>");
        writer.Line($"public static class {className}");
        writer.OpenBrace();

        EmitAllows(writer, stateEnum, entries);

        writer.CloseBrace();
        return writer.ToString();
    }

    private static void EmitAllows(IndentedWriter writer, string stateEnum, ImmutableArray<TypeModel> entries)
    {
        writer.Line($"public static bool Allows({stateEnum} state, byte opcode)");
        writer.OpenBrace();
        writer.Line("return opcode switch");
        writer.OpenBrace();

        foreach (var packet in entries)
        {
            var condition = string.Join(" || ", packet.AllowedStates.Select(s => $"state == ({stateEnum}){s}"));
            writer.Line($"{packet.Opcode} => {condition},");
        }

        writer.Line("_ => true,");
        writer.CloseBraceSemicolon();
        writer.CloseBrace();
    }
}
