CREATE PROCEDURE runtime.usp_SessionTicket_Purge
    WITH NATIVE_COMPILATION ,
        SCHEMABINDING
AS
BEGIN
    ATOMIC
    WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'us_english')
    DELETE
    FROM runtime.SessionTickets
    WHERE ExpiresAtUtc <= SYSUTCDATETIME();
END;
